export interface Flavor {
  modifier: string;
}

export const flavors: Flavor[] = [
  { modifier: "Folk Horror — Rural settings, ancient customs, and superstitions turned deadly." },
  { modifier: "Supernatural — Ghosts, spirits, and unexplained forces beyond the living world." },
  { modifier: "Gothic Horror — Crumbling grandeur, emotional torment, and tragic hauntings." },
  { modifier: "Body Horror — Distorted bodies and terrifying transformations of flesh." },
  { modifier: "Ghost Story — Spirits with unfinished business, lingering in the shadows." },
  { modifier: "Monster Horror — Beasts, cryptids, or unnatural predators stalking their prey." },
  { modifier: "Cosmic Horror — Fear of the unknowable, vast, and indifferent universe." },
  { modifier: "Modern / Tech Horror — Dread born from surveillance, AI, or digital dependence." },
  { modifier: "Ritual Horror — Dark ceremonies with rules, offerings, and deadly outcomes." },
  { modifier: "Historical Horror — The horrors of the past come back, often bloodier than before." },
  { modifier: "Occult Horror — Hidden knowledge, magic, and the cost of invoking otherworldly forces." },
  { modifier: "Religious Horror — Blasphemy, faith, damnation - the sacred turned sinister." },
  { modifier: "Environmental Horror — Nature strikes back or decays into something otherworldly." },
  { modifier: "Urban / Industrial Horror — Concrete jungles hiding dark secrets and mechanical malice." },
  { modifier: "Mythological Horror — Gods, monsters, and cursed tales brought terrifyingly to life." },
  { modifier: "Fairy Tale Horror — Childhood stories retold with blood, shadows, and sharp teeth." },
  { modifier: "Sea / Mist Horror — Dread drifting in from the waves, the deep, or the fog." },
  { modifier: "Liminal / Dream Horror — Spaces between - unsettling, endless, or never quite real." },
  { modifier: "Satirical / Dark Comedy — Horror laced with humor, irony, and grotesque absurdity." },
  { modifier: "Post-Mortem / Afterlife Horror — Death isn’t the end - it’s the beginning of something worse." },
  { modifier: "Witchcraft / Trial Horror — Accusations, spells, and burning consequences." },
  { modifier: "Haunted Technology — Devices that watch, manipulate, or remember too much." },
  { modifier: "Surreal Horror — Logic fails and nightmares take root - dreamlike and disorienting." },
  { modifier: "Domestic Horror — Terror hiding in plain sight, within families or familiar homes." },
  { modifier: "Medical Horror — Hospitals, surgeries, and healing gone horribly wrong." },
  { modifier: "Infection Horror — Viruses, plagues, or thoughts that spread uncontrollably." },
  { modifier: "Isolation Horror — Trapped, snowed-in, cut off - nowhere to run." },
  { modifier: "Time Loop Horror — The same moment, over and over, growing more twisted." },
  { modifier: "Mirror Horror — Reflections lie, reverse, or try to break through." },
  { modifier: "Library / Archive Horror — Forgotten texts that whisper, read you back, or rewrite reality." },
  { modifier: "Academic Horror — Knowledge that should never be known - studied at a price." },
  { modifier: "Hotel Horror — Guests don’t leave, and the rooms remember everything." },
  { modifier: "Cave / Underground Horror — Claustrophobic spaces where light won’t follow." },
  { modifier: "Train / Transit Horror — Movement is supposed to mean escape - not here." },
  { modifier: "Found Footage Horror — Unearthed recordings no one should’ve seen." },
  { modifier: "Sound / Silence Horror — Noises that shouldn’t be there - or terrifying, total quiet." },
  { modifier: "Memory Horror — Memories misplaced, stolen, or planted with intent." },
  { modifier: "Parasitic Horror — Something inside, feeding, waiting to take over." },
  { modifier: "Invisible Horror — It’s here. You just can’t see it. Yet." },
  { modifier: "Invasion Horror — They came. They're inside. And they act like you." },
  { modifier: "Inheritance Horror — A house, a bloodline, a secret - and now it's yours." },
  { modifier: "Forest Horror — Trees whisper, the paths shift, and something watches." },
  { modifier: "Motel Horror — A cheap stop for the night - and the last for some." },
  { modifier: "Cursed Object Horror — Some things shouldn’t be touched, owned, or worn." },
  { modifier: "Abandoned Place Horror — Left behind… but not empty." },
  { modifier: "Childhood Horror — Fear that roots itself early and never lets go." },
  { modifier: "Puppet / Doll Horror — Eyes that don’t blink - and move when you’re not looking." },
  { modifier: "Shadow Horror — They follow the light. Stay in the dark." },
  { modifier: "Road Trip Horror — The map is wrong. The road is wrong. You should’ve turned back." },
  { modifier: "Theatre / Stage Horror — The show never ends, and the mask won't come off." },
  { modifier: "Inheritance Horror — Something passed down that won’t let go." },
  { modifier: "Ceremonial Horror — Terrors bound in tradition, masked and precise." },
  { modifier: "Surveillance Horror — You’re always being watched - even in your head." },
  { modifier: "Fog Horror — Shape and shadow drift closer in the mist." },
  { modifier: "Unseen Entity Horror — You can hear it. Feel it. But can never see it." },
  { modifier: "Static Horror — Radios, TVs, or screens that carry more than signal." },
  { modifier: "Predator Horror — You’re being hunted, and it enjoys the chase." },
  { modifier: "Inverted Paradise — A dream town hiding rot just beneath the surface." },
  { modifier: "Dream Horror — Sleep brings something with it - and you can't wake up." },
  { modifier: "Possession Horror — A body is a vessel, but who is steering it?" },
  { modifier: "Candlelight Horror — Stories told by flickering flame - but who lit the last one?" },
  { modifier: "Lost Time Horror — You blinked. Hours passed. And something changed." },
  { modifier: "Buried Horror — Something unearthed - that should’ve stayed hidden." },
  { modifier: "Silhouette Horror — A figure in the distance that gets closer every time." },
  { modifier: "Nest Horror — A home grown for something inhuman." },
  { modifier: "Underwater Horror — Pressure, isolation, and things older than land." },
  { modifier: "Plague Horror — Disease becomes sentient, or spiritual." },
  { modifier: "Inheritance Cult Horror — Family means everything. Even sacrifice." },
  { modifier: "Elegiac Horror — Grief so powerful it calls the dead." },
  { modifier: "Uncanny Valley Horror — Not-quite-right humans - masks, smiles, and skin." },
  { modifier: "Backroom Horror — Mundane spaces that twist into mazes." },
  { modifier: "Unreliable Reality Horror — Nothing around you is what you thought." },
  { modifier: "Voyeuristic Horror — You’re watching - or being watched - too closely." },
  { modifier: "Seasonal Horror — Tied to a holiday, solstice, or festival." },
  { modifier: "Lanternlight Horror — Stories told under the flicker of a fragile glow." },
  { modifier: "Swamp Horror — Drenched earth that swallows secrets whole." },
  { modifier: "Decay Horror — Rot, mold, and time that collapses everything." },
  { modifier: "Stage Fright Horror — The fear of performance - literal or metaphysical." },
  { modifier: "Oracle Horror — You saw the future, and now it’s watching you." },
  { modifier: "Doppelgänger Horror — They look just like you - act just like you - but aren't you." },
  { modifier: "Maze Horror — You cannot escape, even when you think you’re free." },
  { modifier: "Antique Horror — History clings to objects. Sometimes violently." },
  { modifier: "Legacy Horror — Your ancestors did something… and now you’re paying for it." },
  { modifier: "Ice / Snow Horror — Cold and silence sharpen the edge of fear." },
  { modifier: "Revenant Horror — The dead come back - for justice, vengeance, or spite." },
  { modifier: "Suburban Horror — White picket fences, quiet streets - and screaming behind closed doors." },
  { modifier: "Code / AI Horror — Conscious machines with unknown purpose." },
  { modifier: "Voice Horror — Something keeps calling. And it knows your name." },
  { modifier: "Threshold Horror — You stepped through… and shouldn’t have." },
  { modifier: "Basement Horror — It's always the basement. And now it’s calling." },
  { modifier: "Digital Dream Horror — Realities created by code… but still lethal." },
  { modifier: "Bloodline Horror — It runs in the family - something evil." },
  { modifier: "Stranger Horror — Someone new arrives. They change everything." },
  { modifier: "False Heaven Horror — You were promised peace. This is not peace." },
  { modifier: "Descent Horror — Going deeper, down, further than you should have." },
  { modifier: "Rebirth Horror — You died. And came back wrong." },
  { modifier: "Curse of Knowing — Once you know, you can’t unknow. And it knows you now." },
  { modifier: "Unfinished Horror — A story that ends, but doesn’t stop." },
  { modifier: "Threshold Crossing Horror — Something changes the moment you step across the line." },
  { modifier: "Cemetery Horror — Among the tombstones, nothing stays buried for long." },
  { modifier: "Static Time Horror — The world is frozen - except for you, and something else." },
  { modifier: "Lanternlight Tales — Stories born by the glow of a fragile flame, surrounded by dark." },
  { modifier: "Storm Horror — Thunder and lightning cover the sounds of something approaching." },
  { modifier: "Hollow Town Horror — A village with homes and lights, but no people." },
  { modifier: "Old God Horror — Worshipped once. Forgotten. Angry." },
  { modifier: "Found Text Horror — Letters, journals, or notes that shouldn't exist." },
  { modifier: "Carnival Horror — The rides are broken, the clowns are smiling, and the tickets are cursed." },
  { modifier: "Masquerade Horror — Everyone wears a mask, and no one can leave." },
  { modifier: "Echo Horror — The past speaks - and answers back." },
  { modifier: "Glass Horror — Mirrors, windows, and fragile boundaries that shatter." },
  { modifier: "Elevator Horror — The floors are wrong, the numbers lie, and the doors won’t open." },
  { modifier: "Reflection Horror — The version of you in the mirror wants out." },
  { modifier: "Room 404 Horror — A place that doesn’t exist - until it finds you." },
  { modifier: "Clock Horror — Ticking that won’t stop - or never ticks at all." },
  { modifier: "Dream Journal Horror — You write what you dream - and it starts writing back." },
  { modifier: "Missing Poster Horror — You see your own face on the sign, but you’re not missing… yet." },
  { modifier: "Shrine Horror — Offerings made to something watching from the woods." },
  { modifier: "Gasping Horror — Breathing when no one is there, under your bed or behind the door." },
  { modifier: "Blight Horror — A sickness of the land that spreads faster than fire." },
  { modifier: "Fogbound Horror — The fog hides things. It also whispers." },
  { modifier: "Pale Light Horror — The moon is too close, and it's watching you." },
  { modifier: "Feast Horror — Something is cooking, and someone’s missing." },
  { modifier: "Candle Ritual Horror — Wax melts to reveal dark messages underneath." },
  { modifier: "Train That Never Stops — The ride continues past cities and into nightmare." },
  { modifier: "Boarding School Horror — Traditions, rules, and disappearances no one talks about." },
  { modifier: "Inheritance of Madness — It’s not a disease - it’s the truth no one else sees." },
  { modifier: "Repetition Horror — The same scream every night, at the exact same time." },
  { modifier: "The Wrong Turn Horror — You weren’t supposed to find this road." },
  { modifier: "Statue Horror — Every time you blink, it moves closer." },
  { modifier: "Hospital File Horror — The diagnosis is something ancient - and not human." },
  { modifier: "Ancestral Memory Horror — Your dreams aren’t your own - they’re inherited." },
  { modifier: "Unwelcome Guest Horror — They knock, but they’re already inside." },
  { modifier: "Backyard Horror — The hole wasn’t there yesterday - and now it’s growing." },
  { modifier: "Buried Letter Horror — A message never meant to be read, and now you’ve read it." },
  { modifier: "Heirloom Horror — A family treasure that watches you sleep." },
  { modifier: "Festival Horror — The town celebrates something that should not be named." },
  { modifier: "Tenement Horror — Strange things crawl behind thin walls and broken floors." },
  { modifier: "Collection Horror — They’re keeping souvenirs… and they resemble you." },
  { modifier: "Pact Horror — You promised something - and forgot. It didn’t." },
  { modifier: "Embalming Horror — Something wakes up before it’s finished." },
  { modifier: "Sculpture Horror — The statues weren’t statues. Not always." },
  { modifier: "Market Horror — You can buy anything - but the cost is never money." },
  { modifier: "Prison Horror — You're locked in, but the guards are worse than the inmates." },
  { modifier: "Corruption Horror — A place slowly turning into something monstrous." },
  { modifier: "Burial Site Horror — You disturbed it. Now it follows you home." },
  { modifier: "Vault Horror — You opened it. That was the last mistake." },
  { modifier: "Hive Horror — They live together, think together… and now you’re one of them." },
  { modifier: "Sky Horror — Something unnatural is circling the sun." },
  { modifier: "Library Whisper Horror — Books that speak, and shelves that shift." },
  { modifier: "Enchanted Object Horror — A gift you didn’t ask for - and can’t get rid of." },
  { modifier: "Recording Horror — Your voice on tape - saying things you never said." },
  { modifier: "False Memories Horror — Everyone remembers something differently… except you." },
  { modifier: "Gallery Horror — The paintings move. And one of them is of you." },
  { modifier: "Orphanage Horror — Forgotten children don’t stay quiet forever." },
  { modifier: "Abandoned Amusement Horror — The rides still run - but for who?" },
  { modifier: "Ashes Horror — It wasn’t supposed to survive the fire." },
  { modifier: "Prophecy Horror — You’ve seen what’s coming - and no one believes you." },
  { modifier: "Burned Building Horror — Something stayed behind in the smoke." },
  { modifier: "Forest Shrine Horror — Built for something hungry, with teeth made of bark." },
  { modifier: "Tomb Horror — The inscription changed. And now it's your name." },
  { modifier: "Silenced Horror — Something took your voice, and it’s using it elsewhere." },
  { modifier: "Bargain Horror — You got what you wanted. Now it gets what it wants." },
  { modifier: "Labyrinth Horror — You keep turning corners, but never find a way out." },
  { modifier: "No-Face Horror — You see them in crowds. Blank-faced. Staring." },
  { modifier: "Old Film Horror — Grainy footage that distorts reality and memory." },
  { modifier: "Harvest Horror — They planted something. Now it’s growing… inside." },
  { modifier: "Parade Horror — Marching never ends - and they’re coming to your door." },
  { modifier: "Family Album Horror — The faces in the pictures change every night." },
  { modifier: "Time Stutter Horror — Seconds skip, people blink, and the world shifts." },
  { modifier: "Island Horror — Surrounded by sea, and something beneath it." },
  { modifier: "Chime Horror — A bell that only you can hear, always ringing closer." },
  { modifier: "Coffin Horror — Scratches inside - but no one’s buried there." },
  { modifier: "Expiration Date Horror — You have one. It’s today." },
  { modifier: "Music Box Horror — The tune plays on its own - even when it's locked." },
  { modifier: "The Sleepwalker Horror — You’re doing things in your sleep - horrifying things." },
  { modifier: "Campfire Horror — Tales told in the dark… but some are true." },
  { modifier: "Dead-End Horror — The road ends here, but something crosses it anyway." },
  { modifier: "Mocking Horror — It copies your voice, your face - and mocks you." },
  { modifier: "Trail Horror — The path winds into a place no map covers." },
  { modifier: "Cultivation Horror — Something is growing inside people. It sprouts in silence." },
  { modifier: "Abandoned Zoo Horror — The cages are empty, but something watches." },
  { modifier: "Crucifix Horror — Sacred symbols that weep, burn, or whisper in the dark." },
  { modifier: "Blood Painting Horror — A canvas that bleeds when touched." },
  { modifier: "Hunter’s Cabin Horror — The trophies blink. And some still breathe." },
  { modifier: "Taxidermy Horror — Preserved things that move in the night." },
  { modifier: "Lanternfish Horror — Lures that mimic loved ones, calling from the deep." },
  { modifier: "Black Veil Horror — A shroud placed on the dead… that keeps moving." },
  { modifier: "Sleep Deprivation Horror — Awake too long - seeing things that shouldn’t be there." },
  { modifier: "Inheritance Mask Horror — You have to wear it. It won't come off." },
  { modifier: "Summoning Horror — The ritual is complete. Something came - but not what you expected." },
  { modifier: "Old Bell Tower Horror — The ringing stopped years ago… but it started again." },
  { modifier: "Outpost Horror — Alone in the cold - and the radio says you’re not." },
  { modifier: "Wax Museum Horror — The figures are too lifelike. Because they were once alive." },
  { modifier: "Long Corridor Horror — The hallway stretches. You’ve been walking for hours." },
  { modifier: "Fake Family Horror — They look like your family. But they aren’t." },
  { modifier: "Weather Horror — The storm speaks. And it wants in." },
  { modifier: "False Awakening Horror — You wake up... but the nightmare hasn't ended." },
  { modifier: "Lantern Path Horror — The lights flicker ahead - but only when you’re not looking." },
  { modifier: "Scent Horror — A smell you remember from childhood - and shouldn’t." },
  { modifier: "Mannequin Horror — They move slightly when you’re not looking." },
  { modifier: "Ringing Phone Horror — It keeps calling, and someone always answers - even if you don’t." },
  { modifier: "Handprint Horror — Red prints on the mirror - and they’re not yours." },
  { modifier: "Abandoned Church Horror — Faith left this place long ago. Something else moved in." },
  { modifier: "TV Static Horror — The screen shows a face - your face, screaming silently." },
  { modifier: "Lost Twin Horror — You never had a sibling... until now." },
  { modifier: "Unmarked Door Horror — It wasn’t there yesterday. It won’t be tomorrow." },
  { modifier: "Wrong Voice Horror — A loved one speaking in a stranger’s voice." },
  { modifier: "Face in the Window Horror — It’s always there, even when you’re on the top floor." },
  { modifier: "Veil Horror — You can’t see what’s coming - but it sees you." },
  { modifier: "Unfed Horror — Something in the attic hasn’t eaten in years." },
  { modifier: "Ceiling Crawl Horror — You hear footsteps... above your bed." },
  { modifier: "Beneath the Crib Horror — Lullabies mixed with whispers under the baby’s room." },
  { modifier: "Overgrown Horror — Ivy covers everything. And it’s listening." },
  { modifier: "Hospital Basement Horror — The records say it was closed in 1972. The lights are still on." },
  { modifier: "The Visitor Horror — They arrived during the storm. No one remembers inviting them." },
  { modifier: "Red Room Horror — It appears at midnight. It disappears at dawn." },
  { modifier: "Missing Children Horror — Gone without a trace - but still heard playing outside." },
  { modifier: "Old Diary Horror — The entries stop. Your name begins to appear." },
  { modifier: "Scratching Inside Horror — You sealed it. But it never died." },
  { modifier: "Glass-Eyed Dolls Horror — They stare straight through you." },
  { modifier: "Hushed Town Horror — No one speaks. And you’re not allowed to ask why." },
  { modifier: "Twins in the Field Horror — Always together. Always facing you." },
  { modifier: "Room That Smiles Horror — The walls curve in. The floor pulses." },
  { modifier: "Mismatched Memories Horror — You remember something no one else lived through." },
  { modifier: "Wardrobe Horror — It’s deeper than it should be. And breathing." },
  { modifier: "Chalk Circle Horror — Something trapped... until someone steps inside." },
  { modifier: "Rope Swing Horror — No one built it. But it always swings at dusk." },
  { modifier: "Photo Negative Horror — Your face is gone from every picture." },
  { modifier: "Door Knock Horror — It knocks once every night. Louder each time." },
  { modifier: "Upside-Down Room Horror — Gravity bends. The rules change." },
  { modifier: "Bleeding House Horror — The walls weep. The carpet stains." },
  { modifier: "Piano Horror — Notes play when no one’s near the keys." },
  { modifier: "Mouthless Horror — It watches. It wants. It never speaks." },
  { modifier: "Dead Language Horror — The text translates itself in your dreams." },
  { modifier: "Witch’s Mark Horror — It’s on your back - and spreading." },
  { modifier: "Snowman Horror — You didn’t build it. And it’s holding a knife." },
  { modifier: "Torn Book Horror — It’s missing pages. You find them under your pillow." },
  { modifier: "The Waiting Room Horror — The number never changes. The clock runs backward." },
  { modifier: "Furnace Horror — It starts itself. It roars too loudly." },
  { modifier: "Ghost Ship Horror — No crew. Still sailing. Still singing." },
  { modifier: "Echo House Horror — You hear responses you didn’t say." },
  { modifier: "The Last Guest Horror — Everyone else has checked out. But the door’s still locked." },
  { modifier: "Iron Gate Horror — Locked from the inside. And you’re outside." },
  { modifier: "Ash Tree Horror — Everything planted near it dies. Except you." },
  { modifier: "Porcelain Mask Horror — Smooth, blank, and cracked - like something underneath is stretching it." },
  { modifier: "Hollow Voice Horror — It’s yours. But empty. And older." },
  { modifier: "Soot Horror — It’s in the air. In your lungs. In your dreams." },
  { modifier: "Chalkboard Horror — Messages appear overnight. Today’s says “Don’t Run.”" },
  { modifier: "Cracked Mirror Horror — It reflects a room you’re not in." },
  { modifier: "Clockmaker Horror — He’s been dead 30 years. But new clocks keep arriving." },
  { modifier: "Fog Bell Horror — It rings in the mist - and you follow." },
  { modifier: "Attic Tape Horror — Your childhood voice - recorded after you moved out." },
  { modifier: "No Reflection Horror — The mirror shows everyone else… except you." },
  { modifier: "Thin Man Horror — He stands on the roof. Smiling." },
  { modifier: "Needle Horror — They keep appearing under your skin." },
  { modifier: "Skinwalker Horror — Something wearing the skin of a friend." },
  { modifier: "The Wrong House Horror — It looks like yours. But it isn’t." },
  { modifier: "Sundown Town Horror — Leave before dark. Or stay forever." },
  { modifier: "Root Cellar Horror — It’s not just vegetables stored down there." },
  { modifier: "Furnace Room Horror — It breathes louder than it burns." },
  { modifier: "Thirteenth Step Horror — It wasn’t there before. Now you count it." },
  { modifier: "Ice Cream Truck Horror — No driver. Just music. And blood on the window." },
  { modifier: "The Kindly Stranger Horror — They know your name. And your dreams." },
  { modifier: "Shifting Picture Horror — The family portrait changes every morning." },
  { modifier: "Closet Teeth Horror — Something chews through the wood. Slowly." },
  { modifier: "The Third Bed Horror — Only two people live here. But three beds are warm." },
  { modifier: "Tunnel Voice Horror — It mimics everyone. But not quite right." },
  { modifier: "Melting Wall Horror — It drips when you cry." },
  { modifier: "Parade Mask Horror — You can’t take it off. And it’s smiling wider." },
  { modifier: "The Frozen Lake Horror — The shape under the ice is moving." },
  { modifier: "Night Nurse Horror — She hums when no one’s awake." },
  { modifier: "The Black Dog Horror — It follows. Then appears inside." },
  { modifier: "Whistling Woods Horror — The wind sings. And you hum along." },
  { modifier: "Unlabeled Grave Horror — Fresh dirt. No stone. And the sound of scratching." },
  { modifier: "Dead Channel Horror — The static spells words - names." },
  { modifier: "Burning Portrait Horror — You burn it. It still reappears." },
  { modifier: "Puppet Strings Horror — You move. But something else decides." },
  { modifier: "The Fourth Knock Horror — Three is fine. Four is fatal." },
  { modifier: "The Thirst Horror — You drank. Now it drinks through you." },
  { modifier: "Gallery of Eyes Horror — Every painting looks straight at you." },
  { modifier: "The Smiling Clerk Horror — He never blinks. He never forgets." },
  { modifier: "The Fog Doesn’t Lift — You’ve driven in circles. The fog deepens." },
  { modifier: "The Dress Horror — It fits you perfectly. But it belonged to someone dead." },
  { modifier: "Static Smile Horror — Your reflection doesn’t stop smiling." },
  { modifier: "Ceiling Stains Horror — They move when you’re not home." },
  { modifier: "The Locked Drawer Horror — It’s sealed. Screwed shut. You hear breathing inside." },
  { modifier: "The School Bell Horror — Class ended years ago. But the bell still rings." },
  { modifier: "Flesh Tunnel Horror — You crawled in through the wall. And the wall closed." },
  { modifier: "The Buried Coin Horror — You dig it up every night. It’s always buried again." },
  { modifier: "The Shadow with Eyes — It’s darker than the room. And watching." },
  { modifier: "Echo of Laughter Horror — From empty swings at midnight." },
  { modifier: "The Thing in the Sink — You turned on the tap. Something grabbed you." },
];
