export interface Twist {
  modifier: string;
}

export const twists: Twist[] = [
  { modifier: "Frame this story around a decaying mind, where the protagonist may be haunted… or simply mad." },
  { modifier: "Set the tale in a crumbling mansion where the walls seem to breathe and mourn." },
  { modifier: "Retell the story as a confession letter, written in poetic horror from a prison cell." },
  { modifier: "Make the protagonist obsessed with a singular object - a raven, a clock, a heartbeat." },
  { modifier: "Turn the prompt into a tale of premature burial and rising panic beneath the earth." },
  { modifier: "Set it within a claustrophobic, candlelit chamber haunted by guilt and forgotten sins." },
  { modifier: "Write this as a final entry in a madman’s diary, trailing into illegibility." },
  { modifier: "Imagine this as a duel between two minds unraveling - each sure the other is cursed." },
  { modifier: "Let the horror unfold through the rhythm of repetition, like a cursed poem gone mad." },
  { modifier: "Retell this as a ghost story found in a forgotten manuscript in an old cathedral archive." },
  { modifier: "Frame the tale around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Set this in a quiet countryside where locals refuse to speak of the thing buried beneath the church." },
  { modifier: "Let the horror unfold slowly, through strange markings, mislaid letters, and ghostly visions glimpsed at the edge of sight." },
  { modifier: "Tell it from the point of view of a retired professor whose memories are becoming dangerous." },
  { modifier: "Build the story around a cursed artifact - a whistle, a mirror, or a piece of parchment - that should never have been touched." },
  { modifier: "Set the prompt in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Have the protagonist uncover a warning scrawled centuries ago - and then ignore it." },
  { modifier: "Make the story seem safe at first, then let it turn with one chilling sentence." },
  { modifier: "End with a line that suggests the haunting has now reached the reader too." },
  { modifier: "Tell this as a polite conversation that slowly unravels into quiet terror." },
  { modifier: "Retell it as a story about a woman who no longer trusts her house - or her husband." },
  { modifier: "Frame the horror as something unspoken in a small town where everyone smiles too much." },
  { modifier: "Set it in a boarding house or family home where the rules seem to shift when no one’s looking." },
  { modifier: "Let the narrator be unsure if they’re seeing ghosts or simply being cruelly ignored." },
  { modifier: "Build it around a social faux pas - a missed invitation, a broken teacup - that changes everything." },
  { modifier: "Have a protagonist who wants desperately to be liked, even as things turn eerie." },
  { modifier: "Make the story feel like a letter you weren’t supposed to read, from someone unraveling." },
  { modifier: "Keep the horror offscreen - just glances, silences, and locked rooms." },
  { modifier: "End with a question the reader can’t answer: who was really at fault?" },
  { modifier: "Retell this as a descent into madness triggered by an ancient book no one was meant to read." },
  { modifier: "Set the story in a crumbling coastal town where the tide brings more than just seaweed." },
  { modifier: "Let the protagonist be a rational scholar who slowly loses their grip on reality while uncovering something older than time." },
  { modifier: "Frame this as the recovered journal of someone who vanished after uttering the same phrase every night for weeks." },
  { modifier: "Tell it as a tale of inherited madness - a family secret whispered by tentacled dreams." },
  { modifier: "Reveal only fragments of the truth - through broken rituals, misremembered names, and a sketch of something with too many eyes." },
  { modifier: "Place the horror beneath the surface - in the earth, the ocean, or the stars - always waiting." },
  { modifier: "Turn the prompt into a revelation that language itself is infected with something ancient." },
  { modifier: "End with the suggestion that the reader has already begun the ritual by reading this far." },
  { modifier: "Make the story unravel spatial logic - doors in the wrong places, shadows that move, stars that shouldn’t exist." },
  { modifier: "Retell this as a story where the protagonist slowly realises they are not who they believed themselves to be." },
  { modifier: "Frame the tale in a grand but crumbling estate on the cliffs, where a former resident still lingers - in memory or in truth." },
  { modifier: "Let the horror grow from obsession - with a person, a portrait, or a past event that cannot be let go." },
  { modifier: "Tell it through the eyes of someone entering a new life - marriage, employment, or inheritance - that quickly turns strange." },
  { modifier: "Make the house a character: elegant, decaying, and hiding something under the floorboards." },
  { modifier: "Have the protagonist investigate a woman everyone refuses to speak about, whose presence still dominates everything." },
  { modifier: "Tell the story like a dream of romance, slowly rotting from the inside out." },
  { modifier: "Let the narrator discover old letters or diaries that suggest their life is a repetition of someone else’s tragedy." },
  { modifier: "Use weather and setting - fog, storms, silence - to reflect mounting dread and emotional collapse." },
  { modifier: "End on a note of ambiguity: was it love, revenge, or both?" },
  { modifier: "Retell this as a mythic tale where pain is the price of revelation - and the body bears the scars." },
  { modifier: "Make the horror sensual, intimate, and terrifyingly beautiful - where desire and fear become indistinguishable." },
  { modifier: "Frame the story around a forbidden ritual that promises ecstasy… but demands flesh." },
  { modifier: "Tell it through the eyes of someone willingly changing into something monstrous, and glorious." },
  { modifier: "Introduce a hidden world - behind mirrors, beneath skin, beyond normal perception - that seduces and destroys." },
  { modifier: "Make the antagonist a being of pure hunger or pleasure - not evil, just elemental." },
  { modifier: "Set the story in an abandoned theatre, tattoo parlour, or subterranean temple carved from bone and ink." },
  { modifier: "Turn the protagonist into an artist whose medium becomes blood, skin, or pain." },
  { modifier: "Let a lover return, transformed by something that touched them in the dark." },
  { modifier: "End with the suggestion that this transformation was always waiting - the horror is that they *wanted* it." },
  { modifier: "Retell this as a fairy tale warped by desire, defiance, and blood." },
  { modifier: "Let the protagonist be a girl who refuses to play by the rules - and changes the story’s ending." },
  { modifier: "Frame it in a forest that breathes, where hunger and magic are one and the same." },
  { modifier: "Turn the horror into a coming-of-age - but filled with teeth, mirrors, and velvet shadows." },
  { modifier: "Set the story in a lavish gothic house ruled by rituals of femininity… and revenge." },
  { modifier: "Make the tale sensual, poetic, and soaked in fur, silk, or ash." },
  { modifier: "Tell it as a reimagined nursery rhyme with a dark, adult undertone." },
  { modifier: "Have animals speak truths, lovers wear masks, and wolves whisper beneath skirts." },
  { modifier: "Let transformation be liberation - even when it costs the protagonist their body or name." },
  { modifier: "End on a reclaimed moment of power: a kiss reversed, a knife drawn, a name spoken aloud." },
  { modifier: "Retell this as a small-town horror where everyone knows, but no one talks about it." },
  { modifier: "Set the story in the summer of 1984 - bicycles, baseball, and something evil in the storm drain." },
  { modifier: "Let the horror stem from a childhood event that the protagonist has spent decades trying to forget." },
  { modifier: "Make the threat something ordinary - a dog, a truck, a neighbour - made terrifying by proximity." },
  { modifier: "Frame the story around a group of misfit friends who stumble on something they were never meant to see." },
  { modifier: "Tell it through dual timelines - childhood and adulthood - with something horrific bridging the gap." },
  { modifier: "Have a protagonist struggle with addiction, only to realise sobriety has made the haunting *clearer*." },
  { modifier: "Set it in a decaying town where buildings are closing, but one place - the worst one - stays open." },
  { modifier: "Let the horror be connected to a long-dead parent’s belongings, discovered in the attic." },
  { modifier: "End with a radio static, a children’s rhyme, or a smile from someone who should be long gone." },
  { modifier: "Retell this with no clear resolution - let it feel like waking from a dream you’re not sure was yours." },
  { modifier: "Set the story in a building with too many hallways and doors that never open the same way twice." },
  { modifier: "Let the protagonist follow an invitation they never accepted, to a party that may not have happened." },
  { modifier: "Frame the tale as an anecdote overheard - believable, until the details begin to shift." },
  { modifier: "Tell it as if every sentence is holding something back - the horror lies in what’s *missing*." },
  { modifier: "Make the setting just a little… off. A hotel with no staff. A town with no clocks. A map that loops." },
  { modifier: "Have the protagonist encounter a person who insists they’ve met before - but they haven’t. Or have they?" },
  { modifier: "Let the haunting be something quiet: the sound of breathing behind wallpaper, a repeated word, an old tune." },
  { modifier: "Use architecture as unease - strange floorplans, impossible geometry, staircases to nowhere." },
  { modifier: "End with the suggestion that the protagonist has always lived here, even if they don’t remember arriving." },
  { modifier: "Retell this as a dark fable where forgotten gods linger in alleys and attics." },
  { modifier: "Let the protagonist be a child who sees the truth adults have learned to ignore." },
  { modifier: "Frame the horror in a polite English town where something very old lives beneath the library." },
  { modifier: "Set the story in a house that doesn’t always exist, except on certain nights." },
  { modifier: "Make the tale feel like an old bedtime story, retold with a sinister twist." },
  { modifier: "Have animals speak in riddles, the moon behave strangely, and books whisper warnings." },
  { modifier: "Let the horror be whimsical until it suddenly, terribly isn’t." },
  { modifier: "Use language like a spell - lyrical, quiet, and full of teeth beneath the velvet." },
  { modifier: "Introduce a stranger who trades stories for memories… and never gives them back." },
  { modifier: "End with something lost being found - but not quite the way it was before." },
  { modifier: "Retell this as a haunting that runs through generations, tied to blood and memory." },
  { modifier: "Frame it as a story about inherited pain - and the power or burden that comes with it." },
  { modifier: "Let the protagonist uncover a family secret through dreams passed down like heirlooms." },
  { modifier: "Tell it as a ghost story where the ghost is protecting, not punishing." },
  { modifier: "Set it in a suburban home that holds a violent history beneath the floorboards." },
  { modifier: "Make the horror subtle and emotional - grief as possession, silence as a curse." },
  { modifier: "Reveal that the haunting is part of a legacy the protagonist must choose to accept or break." },
  { modifier: "Use dual timelines: a historical injustice that echoes into the present." },
  { modifier: "Let the horror reveal itself through slow, quiet clues - a name, a smell, a repeated lullaby." },
  { modifier: "End with a moment of intergenerational reckoning: healing, vengeance, or haunting forever." },
  { modifier: "Retell this as a story where the protagonist may not be a person at all." },
  { modifier: "Strip the story to its barest language - let the horror come from what’s not said." },
  { modifier: "Make identity itself unstable - faces change, names repeat, logic collapses." },
  { modifier: "Set it in a sterile environment: a lab, clinic, or bunker - where nothing feels *quite* real." },
  { modifier: "Let the protagonist’s body betray them, subtly, horrifically." },
  { modifier: "Introduce doubles - a second version of the self that behaves differently." },
  { modifier: "Tell it with repetition, fracture, and echo - like a memory gone wrong." },
  { modifier: "Allow no resolution - just a slow bleed of meaning and structure." },
  { modifier: "Have dialogue that trails off or contradicts itself - horror through miscommunication." },
  { modifier: "End with the protagonist unsure whether they’re alive, human, or ever existed at all." },
  { modifier: "Retell this as a ghost story where the haunting is tied to a single unresolved grief." },
  { modifier: "Set it in a bleak rural village where fog clings to memory like ivy on stone." },
  { modifier: "Let the horror manifest gently - footsteps, shadows, the cold touch of loss." },
  { modifier: "Make the protagonist a widower or governess, still aching with unspoken sorrow." },
  { modifier: "Frame it around a child’s toy, photograph, or bedroom untouched since death." },
  { modifier: "Use silence as a weapon - long pauses, empty rooms, unsaid things." },
  { modifier: "Set it in winter, where the landscape is as mournful as the past." },
  { modifier: "Let the ghost only appear in reflections - glimpses on polished surfaces." },
  { modifier: "Tell the story as a letter never sent, filled with longing and a name whispered once." },
  { modifier: "End with a return - not dramatic, but final. The past has caught up quietly." },
  { modifier: "Retell this as a fragmented story - journal entries, interviews, scraps of memory." },
  { modifier: "Let the horror grow from a relationship where boundaries blur and shift." },
  { modifier: "Frame it as a retelling of a fairy tale - but queered, broken, and burning at the edges." },
  { modifier: "Set it in a house that changes based on how its inhabitants treat one another." },
  { modifier: "Tell it from a narrator who admits they are not telling the truth - or can’t remember what it is." },
  { modifier: "Make domesticity uncanny: towels folded too neatly, appliances whispering, rooms rearranging." },
  { modifier: "Let desire and fear bleed into one another - the body as both sanctuary and trap." },
  { modifier: "Introduce a box, a notebook, or a voice memo that cannot be destroyed - and contains too much." },
  { modifier: "Have characters forget themselves mid-scene - faces glitching, names sliding." },
  { modifier: "End with ambiguity: did the horror happen, or was the story the trap all along?" },
  { modifier: "Retell this as a story where nature itself watches - and judges." },
  { modifier: "Set it deep in the woods, where trees seem too tall and too quiet." },
  { modifier: "Frame the story around a character who feels drawn to a place - and shouldn’t be." },
  { modifier: "Let the protagonist witness something impossible in the natural world… and tell no one." },
  { modifier: "Make the horror come not from violence, but from reverence - awe turned to fear." },
  { modifier: "Use the environment as character: fog that thinks, winds that whisper in known voices." },
  { modifier: "Let the protagonist vanish into nature, becoming part of the forest, willingly or not." },
  { modifier: "Introduce an ancient structure - stone circle, cave, hill - that changes those who approach." },
  { modifier: "Let the horror be old, indifferent, and vast - nothing personal, just inevitable." },
  { modifier: "End with silence: no monster, no blood - just emptiness where someone used to be." },
  { modifier: "Retell this as a story of obsession - where one image, word, or gesture repeats until it consumes." },
  { modifier: "Let the horror be visual: spirals, holes, growths, movement where there shouldn’t be." },
  { modifier: "Make the protagonist’s body change in unnatural ways - and be helpless to stop it." },
  { modifier: "Set the story in a town where something is wrong - but no one will leave." },
  { modifier: "Use a seemingly ordinary object - a mirror, a photograph, a house - as a source of mutation." },
  { modifier: "Let logic slowly break: gravity twists, rooms stretch, time loops." },
  { modifier: "Tell it as a warning - left by someone who saw too much and didn’t survive." },
  { modifier: "Introduce a pattern that spreads like a virus - tattoos, architecture, behaviour." },
  { modifier: "Have the horror escalate beyond explanation - just more, and more, and more." },
  { modifier: "End with transformation: not death, but becoming something else entirely." },
  { modifier: "Retell this as a fairy tale that refuses to stay fixed - the characters keep changing roles." },
  { modifier: "Let the protagonist be unsure whether they’re the hunter, the witch, or the girl lost in the woods." },
  { modifier: "Set the story in a modern home with a door that doesn’t lead where it should - or always leads somewhere else." },
  { modifier: "Let the horror be subtle and trickster-like: polite voices, gifts that grow teeth, riddles without answers." },
  { modifier: "Introduce an object - a book, a key, a teacup - that remembers things no one told it." },
  { modifier: "Make characters change names mid-scene, or forget the names of those they love." },
  { modifier: "Let reality flicker: architecture rearranges, timelines skip, language rewrites itself." },
  { modifier: "Frame the tale around a friendship or romance that feels like a spell cast too well." },
  { modifier: "Have characters mirror each other, not quite perfectly - until one starts to crack." },
  { modifier: "End with transformation - gentle, strange, and irreversible." },
  { modifier: "Retell this as a story where the protagonist suspects reality is not only fake - but malicious." },
  { modifier: "Make the narrator increasingly paranoid that they are being controlled - by someone… or something." },
  { modifier: "Set it in a dying town where no one makes eye contact, and every building leans slightly inward." },
  { modifier: "Let the horror be abstract - dread without source, tension without explanation." },
  { modifier: "Introduce strange performances - street mimes, empty circuses, puppet theatres - that seem to reflect inner horrors." },
  { modifier: "Have characters repeat phrases exactly, as if scripted - like reality has run out of lines." },
  { modifier: "Make the environment dissolve subtly: words missing from signs, colours vanishing, sky flickering." },
  { modifier: "Frame the story as a philosophical treatise that slowly becomes a personal confession of terror." },
  { modifier: "Suggest that all of humanity has always been dead - they just haven’t noticed yet." },
  { modifier: "End with a shrug - not relief, not closure. Just futility." },
  { modifier: "Retell this with the warm glow of summer… and something terrible just out of sight." },
  { modifier: "Let the protagonist be a curious child who stumbles on a carnival act that’s older than history." },
  { modifier: "Set the story in a perfect town that quietly rewrites people when they step out of line." },
  { modifier: "Frame it around a memory - dusty sunlight, laughter, and a shadow no one else remembers." },
  { modifier: "Introduce a travelling salesman, librarian, or magician who offers something strange and free." },
  { modifier: "Let the horror be wrapped in wonder: paper moons, autumn leaves, and an impossible smile." },
  { modifier: "Have machines that feel alive, books that write themselves, and trains that never stop." },
  { modifier: "Let the setting be a school, a field, a front porch - the last place you'd expect dread to bloom." },
  { modifier: "Keep the tone lyrical and warm - until the final paragraph." },
  { modifier: "End with a child laughing at something only they can see." },
  { modifier: "Retell this as a grounded horror story where the monster represents something broken inside someone." },
  { modifier: "Set it in a run-down motel, a truck stop, or a rusting industrial town - where emotions fester." },
  { modifier: "Frame the horror as something inherited - not just genetically, but economically or socially." },
  { modifier: "Let the protagonist try to fix something mundane - a car, a house, a job - and find something awful beneath it." },
  { modifier: "Make the horror deeply personal: an addiction, an abusive memory, a missing child." },
  { modifier: "Introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them." },
  { modifier: "Keep the language raw and human - horror that bleeds, not floats." },
  { modifier: "Let love and shame fight each other on the page - both losing." },
  { modifier: "Reveal that the horror was always part of the town - everyone just pretends not to see it." },
  { modifier: "End with a choice: stay, leave, or become part of it." },
  { modifier: "Retell this with glam-gothic flair - like a horror drag show that turns blood into sequins." },
  { modifier: "Make the protagonist perform horror flamboyantly: campy, cruel, and devastatingly fabulous." },
  { modifier: "Frame the tale as a monologue from a cabaret host who might not be entirely human." },
  { modifier: "Let the horror emerge mid-performance - lashes fall off, mirrors crack, voices shift." },
  { modifier: "Tell it like a lost episode of a haunted variety show from the 1970s." },
  { modifier: "Make gender, spectacle, and fear blur into something monstrous but beautiful." },
  { modifier: "End with a spotlight... and a scream." },
  { modifier: "Have a costume be cursed - the wearer can’t take it off without shedding skin." },
  { modifier: "Let the horror be sassily self-aware - the ghost *knows it’s fabulous*." },
  { modifier: "Make the whole thing a cursed audition no one remembers attending." },
  { modifier: "Set the story in a Buenos Aires slum where the streets breathe and cry at night." },
  { modifier: "Let the haunting be political - disappeared voices returning through walls and drains." },
  { modifier: "Frame the tale around a child who feeds something in the basement of a state building." },
  { modifier: "Let the horror emerge from poverty, hunger, or violence - nothing supernatural required." },
  { modifier: "Tell it with fire, ash, and bones - literal or not." },
  { modifier: "Make the characters disappear between paragraphs - like they were never there." },
  { modifier: "End with something ordinary (a coin, a breath, a glance) becoming unbearable." },
  { modifier: "Use graffiti, refuse, or cuts in the pavement as supernatural signs." },
  { modifier: "Tell it from the point of view of a corpse being mourned or denied." },
  { modifier: "Let saints and mothers become indistinguishable - both weeping blood." },
  { modifier: "Write this like a seizure - fractured, sensual, and hard to hold still." },
  { modifier: "Let the story emerge through raw perception: sensation, pain, arousal, distortion." },
  { modifier: "Set it in a theatre of flesh - performance, intimacy, and violence mingling." },
  { modifier: "Make the narrator obsessed with a wound, a smell, a gesture." },
  { modifier: "Frame it around a character slowly disappearing into their own skin." },
  { modifier: "Use typography - repetition, breaks, negative space - to reflect inner trauma." },
  { modifier: "Let the protagonist narrate as if possessed by their own nerves." },
  { modifier: "Make time and space unreliable: a corridor that’s always dark, a face that shifts." },
  { modifier: "End mid-sentence - the horror never resolves, just stops." },
  { modifier: "Let the climax feel like a nervous breakdown in real time." },
  { modifier: "Tell it through a quiet lens: low stakes, low voice, high stakes beneath the surface." },
  { modifier: "Set it in a shared kitchen, apartment hallway, or missed train stop - with something wrong." },
  { modifier: "Let objects vanish and reappear, slightly wrong each time." },
  { modifier: "Make the horror social: judgmental glances, overpoliteness, silences too long." },
  { modifier: "Frame it through newspaper clippings or fragments of text in an unknown language." },
  { modifier: "Let the protagonist do nothing - and still doom everyone." },
  { modifier: "Set the horror in a modern job interview, dinner party, or parent meeting." },
  { modifier: "Use flat language to describe something extraordinary - a woman floating, blood boiling in stillness." },
  { modifier: "Let the supernatural intrude *exactly once*, then never again." },
  { modifier: "End with a smile that never breaks, even after the teeth fall out." },
  { modifier: "Tell this as a story where the forest isn’t just alive - it’s aware and ancient." },
  { modifier: "Let the protagonist feel watched by trees that never move when you're looking." },
  { modifier: "Set it near water: a river that sings, a lake that reflects something wrong." },
  { modifier: "Make the horror spiritual - awe so overwhelming it becomes fear." },
  { modifier: "Frame the tale around a walk that never ends, a clearing that shouldn’t exist." },
  { modifier: "Let the land whisper in old dialects and forgotten birdsong." },
  { modifier: "Use a natural object - a rock, a tree, a fungus - as the source of dread." },
  { modifier: "Have the protagonist become smaller as they walk deeper in." },
  { modifier: "Let nature *invite* them in - and then seal the exit." },
  { modifier: "End with peace… and permanent silence." },
  { modifier: "Retell this as a grotesque obsession - with a face, a smell, a hole in the wall." },
  { modifier: "Set the story in a quiet town where everyone has the same scar, but won’t explain." },
  { modifier: "Let the protagonist discover a pattern that appears on their skin - and spreads." },
  { modifier: "Frame it around a new neighbour who never sleeps and has too many teeth." },
  { modifier: "Make logic melt: heads spin, shadows bend, bodies bloom into awful new shapes." },
  { modifier: "Introduce a well or drain where voices sing at night - backwards." },
  { modifier: "Let the horror be geometric: spirals, orbs, symmetry that becomes unbearable." },
  { modifier: "Use bugs, hair, or water as uncanny motifs." },
  { modifier: "Have characters smile too wide - and then peel." },
  { modifier: "End mid-transformation - human to something *else*." },
  { modifier: "Tell it as a fairy tale where mirrors argue back and shoes lead the wrong way." },
  { modifier: "Set the story in a house with rules written in chalk - rules that rearrange daily." },
  { modifier: "Let the horror be beautiful: honey-dripping wolves, velvet spiders, silk blades." },
  { modifier: "Have two characters switch roles halfway - neither notices, only the reader." },
  { modifier: "Use gentle surrealism - clocks that tick backward, letters in a new alphabet." },
  { modifier: "Introduce a fruit or perfume that changes people subtly." },
  { modifier: "Frame the tale around a sibling rivalry that breaks reality’s bones." },
  { modifier: "Make lies come true and truths dissolve with each telling." },
  { modifier: "End with a name being forgotten - or overwritten." },
  { modifier: "Let the protagonist become the thing they feared - and not mind." },
  { modifier: "Retell this as a philosophical void - a story that denies the possibility of meaning." },
  { modifier: "Let the narrator insist nothing matters - and then prove it horrifically." },
  { modifier: "Set it in a corporate office where people vanish between floors… and no one cares." },
  { modifier: "Make the characters puppets, mannequins, or meat with scripts." },
  { modifier: "Let the story observe - not judge - as a man loses his soul and doesn't notice." },
  { modifier: "Frame it as an orientation manual for a company that doesn’t exist." },
  { modifier: "Use circular logic: every question answered with another paradox." },
  { modifier: "Have architecture whisper - cubicles shifting, walls moaning, elevators laughing." },
  { modifier: "End by looping back to the beginning… but slightly worse." },
  { modifier: "Make the story feel like the world blinking - just once - and everything is wrong." },
  { modifier: "Retell this as a nostalgic Halloween memory… until the mask won’t come off." },
  { modifier: "Set the story in October - always October - with red leaves and black skies." },
  { modifier: "Let the horror live in carousels, old books, candy that melts into teeth." },
  { modifier: "Frame the tale as a bedtime story told *too well*." },
  { modifier: "Make the villain a librarian, a music teacher, a neighbour with glowing eyes." },
  { modifier: "Have something follow the children home - polite, quiet, and full of history." },
  { modifier: "Let the protagonist uncover a fairground built on bones - and tickets never expire." },
  { modifier: "Use autumn imagery: smoke, pumpkins, hay, but twist every scent into dread." },
  { modifier: "Make the horror beautiful and sad - like growing up and never being believed." },
  { modifier: "End with the child grown old… and it still waiting." },
  { modifier: "Frame this as a working-class tragedy - grief made flesh and rage made monstrous." },
  { modifier: "Set it in a trailer park, steel mill, or cheap motel where something waits in the vents." },
  { modifier: "Let the monster reflect addiction, poverty, loss - something real and cruel." },
  { modifier: "Use harsh language, broken grammar, and poetic detail: a cigarette’s glow, rusted light." },
  { modifier: "Tell it through bruises, letters unsent, and wounds that don’t heal right." },
  { modifier: "Let the horror feel inevitable - not a twist, but a slow crush." },
  { modifier: "Make family love the threat - a brother who never came home right, a daughter who’s not quite her." },
  { modifier: "Introduce a relic - a necklace, hammer, or lunchbox - that burns cold." },
  { modifier: "Have the protagonist choose between the real world and the monstrous one… and choose wrong." },
  { modifier: "End with quiet: just a man, a dog, a road. And what's following." },
  { modifier: "Tell this as a ghost story found in a forgotten manuscript in an old cathedral archive. Also, let the protagonist uncover a family secret through dreams passed down like heirlooms." },
  { modifier: "Let the protagonist uncover a family secret through dreams passed down like heirlooms. Also, frame the tale around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Frame the tale around a scholar who unknowingly awakens something ancient during research. Also, introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them." },
  { modifier: "Introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them. Also, set the story in a modern home with a door that doesn’t lead where it should - or always leads somewhere else." },
  { modifier: "Set the story in a modern home with a door that doesn’t lead where it should - or always leads somewhere else. Also, use gentle surrealism - clocks that tick backward, letters in a new alphabet." },
  { modifier: "Use gentle surrealism - clocks that tick backward, letters in a new alphabet. Also, make the antagonist a being of pure hunger or pleasure - not evil, just elemental." },
  { modifier: "Make the antagonist a being of pure hunger or pleasure - not evil, just elemental. Also, tell the story like a dream of romance, slowly rotting from the inside out." },
  { modifier: "Tell the story like a dream of romance, slowly rotting from the inside out. Also, end with a line that suggests the haunting has now reached the reader too." },
  { modifier: "End with a line that suggests the haunting has now reached the reader too. Also, let transformation be liberation - even when it costs the protagonist their body or name." },
  { modifier: "Let transformation be liberation - even when it costs the protagonist their body or name. Also, tell this as a ghost story found in a forgotten manuscript in an old cathedral archive." },
  { modifier: "Let the protagonist uncover a family secret through dreams passed down like heirlooms. Also, frame the tale around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Frame the tale around a scholar who unknowingly awakens something ancient during research. Also, set the story in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Set this in a quiet countryside where locals refuse to speak of the thing buried beneath the church. Also, have the protagonist uncover a warning scrawled centuries ago - and then ignore it." },
  { modifier: "Let the horror unfold slowly, through strange markings, mislaid letters, and ghostly visions glimpsed at the edge of sight. Also, frame the tale around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Tell it from the point of view of a retired professor whose memories are becoming dangerous. Also, make the horror reveal itself through slow, quiet clues - a name, a smell, a repeated lullaby." },
  { modifier: "Build the story around a cursed artifact - a whistle, a mirror, or a piece of parchment - that should never have been touched. Also, set the prompt in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Set the prompt in a seaside town with a strange bell that rings only in fog. Also, end with a line that suggests the haunting has now reached the reader too." },
  { modifier: "Frame the tale around a scholar who unknowingly awakens something ancient during research. Also, have the protagonist investigate a woman everyone refuses to speak about, whose presence still dominates everything." },
  { modifier: "Have the protagonist investigate a woman everyone refuses to speak about, whose presence still dominates everything. Also, tell it as a final entry in a madman’s diary, trailing into illegibility." },
  { modifier: "Tell it through the eyes of someone entering a new life - marriage, employment, or inheritance - that quickly turns strange. Also, set it in a crumbling mansion where the walls seem to breathe and mourn." },
  { modifier: "Let the protagonist become obsessed with a singular object - a raven, a clock, a heartbeat. Also, make the story seem safe at first, then let it turn with one chilling sentence." },
  { modifier: "Make the story feel like a letter you weren’t supposed to read, from someone unraveling. Also, tell it as a ghost story found in a forgotten manuscript in an old cathedral archive." },
  { modifier: "Let the horror unfold through the rhythm of repetition, like a cursed poem gone mad. Also, frame the tale around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Retell this as a ghost story found in a forgotten manuscript in an old cathedral archive. Also, let the horror be wrapped in wonder: paper moons, autumn leaves, and an impossible smile." },
  { modifier: "Set it within a claustrophobic, candlelit chamber haunted by guilt and forgotten sins. Also, let the horror be visual: spirals, holes, growths, movement where there shouldn’t be." },
  { modifier: "Frame it around a relationship where the boundaries blur and shift. Also, let the protagonist witness something impossible in the natural world… and tell no one." },
  { modifier: "Introduce a hidden world - behind mirrors, beneath skin, beyond normal perception - that seduces and destroys. Also, set the story in a perfect town that quietly rewrites people when they step out of line." },
  { modifier: "Let the protagonist be unsure whether they’re the hunter, the witch, or the girl lost in the woods. Also, set the story in a hotel with no staff. A town with no clocks. A map that loops." },
  { modifier: "Let the protagonist become smaller as they walk deeper in. Also, set it in a modern home with a door that doesn’t lead where it should - or always leads somewhere else." },
  { modifier: "Introduce a stranger who trades stories for memories… and never gives them back. Also, set the story in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Let the protagonist slowly become someone they fear - until they’re not sure if they’re still human. Also, end with a moment of intergenerational reckoning: healing, vengeance, or haunting forever." },
  { modifier: "Retell this as a fragmented story - journal entries, interviews, scraps of memory. Also, set the story in a decaying town where buildings are closing, but one place - the worst one - stays open." },
  { modifier: "Tell it through the eyes of a child who sees the truth adults have learned to ignore. Also, let the horror be wrapped in wonder: paper moons, autumn leaves, and an impossible smile." },
  { modifier: "Make the story unravel spatial logic - doors in the wrong places, shadows that move, stars that shouldn’t exist. Also, introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them." },
  { modifier: "Set it in a hotel with no staff. A town with no clocks. A map that loops. Also, let the protagonist become the thing they feared - and not mind." },
  { modifier: "Introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them. Also, let transformation be liberation - even when it costs the protagonist their body or name." },
  { modifier: "End with a smile that never breaks, even after the teeth fall out. Also, set the prompt in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Set the story in a quiet countryside where locals refuse to speak of the thing buried beneath the church. Also, frame it around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Make the protagonist obsessed with a singular object - a raven, a clock, a heartbeat. Also, tell it through the eyes of a child who sees the truth adults have learned to ignore." },
  { modifier: "Frame the tale around a relationship where the boundaries blur and shift. Also, let the horror unfold through the rhythm of repetition, like a cursed poem gone mad." },
  { modifier: "Set the story in a crumbling coastal town where the tide brings more than just seaweed. Also, let the protagonist uncover a warning scrawled centuries ago - and then ignore it." },
  { modifier: "Introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them. Also, set it within a claustrophobic, candlelit chamber haunted by guilt and forgotten sins." },
  { modifier: "Frame it as a retelling of a fairy tale - but queered, broken, and burning at the edges. Also, let the protagonist slowly realise they are not who they believed themselves to be." },
  { modifier: "Let the protagonist discover old letters or diaries that suggest their life is a repetition of someone else’s tragedy. Also, end with a moment of intergenerational reckoning: healing, vengeance, or haunting forever." },
  { modifier: "Tell the story through the eyes of a child who sees the truth adults have learned to ignore. Also, make the horror stem from a childhood event that the protagonist has spent decades trying to forget." },
  { modifier: "Let the horror grow from obsession - with a person, a portrait, or a past event that cannot be let go. Also, make the setting just a little… off. A hotel with no staff. A town with no clocks." },
  { modifier: "End on a note of ambiguity: was it love, revenge, or both? Also, make the horror reveal itself through slow, quiet clues - a name, a smell, a repeated lullaby." },
  { modifier: "Frame it as a story where the protagonist suspects reality is not only fake - but malicious. Also, set the story in a perfect town that quietly rewrites people when they step out of line." },
  { modifier: "Let the horror stem from a childhood event that the protagonist has spent decades trying to forget. Also, tell it through the eyes of someone entering a new life - marriage, employment, or inheritance - that quickly turns strange." },
  { modifier: "Set it in an abandoned theatre, tattoo parlour, or subterranean temple carved from bone and ink. Also, make the protagonist a woman who no longer trusts her house - or her husband." },
  { modifier: "Set the story in a crumbling coastal town where the tide brings more than just seaweed. Also, tell it as a fairy tale warped by desire, defiance, and blood." },
  { modifier: "Set it deep in the woods, where trees seem too tall and too quiet. Also, tell it through the eyes of someone willing to change into something monstrous, and glorious." },
  { modifier: "Make the antagonist a being of pure hunger or pleasure - not evil, just elemental. Also, let the horror be visual: spirals, holes, growths, movement where there shouldn’t be." },
  { modifier: "Let the protagonist witness something impossible in the natural world… and tell no one. Also, use gentle surrealism - clocks that tick backward, letters in a new alphabet." },
  { modifier: "Introduce a strange performance - street mimes, empty circuses, puppet theatres - that seems to reflect inner horrors. Also, turn the protagonist into an artist whose medium becomes blood, skin, or pain." },
  { modifier: "Frame the story around a haunted object - a whistle, a mirror, or a piece of parchment - that should never have been touched. Also, let the protagonist slowly become someone they fear - until they’re not sure if they’re still human." },
  { modifier: "Set it in a rundown motel, a truck stop, or a rusting industrial town - where emotions fester. Also, introduce a creature that seems to reflect the protagonist’s worst thoughts - or feed on them." },
  { modifier: "Have a protagonist who wants desperately to be liked, even as things turn eerie. Also, turn it into a haunting where something is inherited - not just genetically, but economically or socially." },
  { modifier: "Frame it as a reimagined nursery rhyme with a dark, adult undertone. Also, let the horror grow from obsession - with a person, a portrait, or a past event that cannot be let go." },
  { modifier: "Let the protagonist slowly realise they are not who they believed themselves to be. Also, tell it from the point of view of a retired professor whose memories are becoming dangerous." },
  { modifier: "Set the story in a crumbling mansion where the walls seem to breathe and mourn. Also, tell it through the eyes of someone entering a new life - marriage, employment, or inheritance - that quickly turns strange." },
  { modifier: "Let the protagonist’s body betray them, subtly, horrifically. Also, set the story in a modern home with a door that doesn’t lead where it should - or always leads somewhere else." },
  { modifier: "End with a question the reader can’t answer: who was really at fault? Also, set the story in a seaside town with a strange bell that rings only in fog." },
  { modifier: "Set it in a building with too many hallways and doors that never open the same way twice. Also, end with a smile that never breaks, even after the teeth fall out." },
  { modifier: "Tell the story through the eyes of a child who sees the truth adults have learned to ignore. Also, set it deep in the woods, where trees seem too tall and too quiet." },
  { modifier: "Frame the tale around a family secret whispered by tentacled dreams. Also, tell it through the eyes of a child who sees the truth adults have learned to ignore." },
  { modifier: "Introduce a stranger who trades stories for memories… and never gives them back. Also, set the story in a quiet countryside where locals refuse to speak of the thing buried beneath the church." },
  { modifier: "Set it in a run-down motel, a truck stop, or a rusting industrial town - where emotions fester. Also, make the setting just a little… off. A hotel with no staff. A town with no clocks." },
  { modifier: "Let the protagonist discover old letters or diaries that suggest their life is a repetition of someone else’s tragedy. Also, introduce a strange performance - street mimes, empty circuses, puppet theatres." },
  { modifier: "Let the protagonist be a curious child who stumbles on a carnival act that’s older than history. Also, frame it around a new neighbour who never sleeps and has too many teeth." },
  { modifier: "Frame the tale around a group of misfit friends who stumble on something they were never meant to see. Also, have a protagonist who wants desperately to be liked, even as things turn eerie." },
  { modifier: "Set the story in a quiet town where everyone has the same scar, but won’t explain. Also, let the horror grow from obsession - with a person, a portrait, or a past event that cannot be let go." },
  { modifier: "Make the horror stem from a childhood event that the protagonist has spent decades trying to forget. Also, frame it as a story about a woman who no longer trusts her house - or her husband." },
  { modifier: "Set it in a haunted village where time stops on certain nights. Also, frame it around a scholar who unknowingly awakens something ancient during research." },
  { modifier: "Let the horror manifest subtly - footsteps, shadows, the cold touch of loss. Also, have the protagonist uncover a warning scrawled centuries ago - and then ignore it." },
  { modifier: "Frame it as a reimagined nursery rhyme with a dark, adult undertone. Also, set it within a claustrophobic, candlelit chamber haunted by guilt and forgotten sins." },
  { modifier: "End with a line that suggests the haunting has now reached the reader too. Also, set it deep in the woods, where trees seem too tall and too quiet." },
  { modifier: "Introduce a hidden world - behind mirrors, beneath skin, beyond normal perception - that seduces and destroys. Also, tell it as a final entry in a madman’s diary, trailing into illegibility." },
  { modifier: "Let the horror grow from obsession - with a person, a portrait, or a past event that cannot be let go. Also, tell the story like a dream of romance, slowly rotting from the inside out." },
  { modifier: "Let transformation be liberation - even when it costs the protagonist their body or name. Also, tell it through the eyes of someone willing to change into something monstrous, and glorious." },
  { modifier: "Retell this as a tale of ancient gods disguised as everyday objects." },
  { modifier: "Frame the story around an unspoken pact that haunts a family’s legacy for generations." },
  { modifier: "Set the horror within a virtual world that’s slowly eating through the real one." },
  { modifier: "Let the monster be an old melody - a song that plays in the back of the mind, driving the protagonist mad." },
  { modifier: "Introduce a creature that only exists when the protagonist isn’t looking." },
  { modifier: "Frame it as a whispered legend that turns into a cursed truth as the protagonist investigates." },
  { modifier: "Set the story inside a dying city - its streets haunted by the ghosts of people who fled." },
  { modifier: "Let the protagonist become a medium for an ancient entity that speaks through them." },
  { modifier: "Tell the tale through a series of cryptic messages sent by a deceased loved one." },
  { modifier: "Have a mysterious artifact slowly re-write the protagonist’s past." },
  { modifier: "Frame the story around a childhood memory that doesn’t quite match the reality when revisited." },
  { modifier: "Set the horror in a realm where time flows backward, unraveling the protagonist’s reality." },
  { modifier: "Let the horror be a deep-seated fear that the protagonist has always carried but never acknowledged." },
  { modifier: "Make the protagonist’s fear so powerful that it materializes into something physical." },
  { modifier: "Retell this as a world where all clocks stop at exactly the same moment every day." },
  { modifier: "Frame the story around a group of friends who realize they’ve all been living the same nightmare." },
  { modifier: "Let the protagonist come across a diary from the future, which predicts their every move - and worse, their end." },
  { modifier: "Set it in a perfect town that hasn’t changed in 100 years, until someone finally notices the dark secret." },
  { modifier: "Tell the tale as a fragmented dream that never quite comes together - until the final horrifying clarity." },
  { modifier: "Let the protagonist enter a forgotten library, where every book is a doorway to a different life they could’ve lived." },
  { modifier: "Set the story within the confines of a house that keeps changing its layout when no one is looking." },
  { modifier: "Let the ghost tormenting the protagonist be an exact copy of their future self, warning them of doom." },
  { modifier: "Frame it as a secret club where members must trade their most precious memories to stay in." },
  { modifier: "Introduce a mirror that shows the protagonist’s true self - a version they never dared to face." },
  { modifier: "Set the tale in a town where everyone wears masks to hide their darkest secrets - but one mask is starting to crack." },
  { modifier: "Let the protagonist try to solve a murder, only to realize they’re the one being haunted by the victim." },
  { modifier: "Retell this as a creature that feeds on guilt and only grows stronger as the protagonist tries to evade it." },
  { modifier: "Frame it around a new neighbour who never sleeps and has too many teeth." },
  { modifier: "Set the story in a house with rules written in chalk - rules that rearrange daily." },
  { modifier: "Let the horror emerge through raw perception: sensation, pain, arousal, distortion." },
  { modifier: "Set it in a town where all the children are gone, and the adults live in a strange, perpetual silence." },
  { modifier: "Introduce a world where the protagonist is haunted by their own forgotten memories." },
  { modifier: "Frame the tale around a woman who refuses to speak her mind and suffers for it in terrifying ways." },
  { modifier: "Set it in a seaside town with an ancient bell that rings only in fog, but no one remembers why." },
  { modifier: "Let the protagonist confront a truth that has been buried for centuries - and buried in blood." },
  { modifier: "Frame the story as a love letter from a madman, rewriting history to make the protagonist its final subject." },
  { modifier: "Set the tale inside a grand mansion - but the rooms keep changing, and the servants are not who they seem." },
  { modifier: "Have the protagonist struggle with addiction, only to realize sobriety has made the haunting *clearer*." },
  { modifier: "Set the story in a decaying town where buildings are closing, but one place - the worst one - stays open." },
  { modifier: "Let the horror be tied to a childhood event that the protagonist has spent decades trying to forget." },
  { modifier: "Introduce a door that opens to a room that shouldn’t exist - a door that *shouldn’t be there*." },
  { modifier: "Have a protagonist who is convinced they are not the person they once were." },
  { modifier: "Set the story in a rural village where every family carries a tragic secret - and one secret can never be revealed." },
  { modifier: "Tell it as if the protagonist were already dead, and the world has become their afterlife." },
  { modifier: "Frame the tale as a puzzle box with the protagonist slowly unwrapping their own tragic fate." },
  { modifier: "End with the revelation that the protagonist was the cause of their own suffering, only they’ve forgotten how." },
  { modifier: "Tell the horror as a *quiet scream*, a subtle feeling of dread that follows the protagonist wherever they go." },
  { modifier: "Frame the story as a cautionary tale - but the protagonist doesn’t believe in the warning until it’s too late." },
  { modifier: "Introduce a world where the protagonist becomes the villain in their own story - and can never go back." },
  { modifier: "End with the suggestion that this horror will repeat - not for the protagonist, but for the reader." },
  { modifier: "Set the story in a town where every building is a replica of a house in the protagonist’s past, and they can’t escape." },
  { modifier: "Frame it as a supernatural court case, where the protagonist is being tried by ghosts from their past life." },
  { modifier: "Have the protagonist uncover a mirror that shows them what they *could have been* - and it's terrifying." },
  { modifier: "Introduce a group of people who are cursed to relive the same traumatic event, but with a new twist each time." },
  { modifier: "Let the protagonist stumble upon a house of mirrors, but in each reflection, something sinister waits." },
  { modifier: "Tell it as if the protagonist is already dead, but no one has told them yet." },
  { modifier: "Set the story in a remote village where the protagonist is the last to realize everyone else has already died." },
  { modifier: "Have the protagonist uncover a letter from the past that warns of something they’re about to do - but they don't heed it." },
  { modifier: "Frame the story around a haunted piece of technology that starts to learn the protagonist’s secrets." },
  { modifier: "Make the horror psychological: a gradually escalating obsession that consumes the protagonist’s life." },
  { modifier: "Set the story in a hospital where the patients are the doctors and vice versa - and neither is quite human." },
  { modifier: "Let the protagonist realize they’ve been dead all along - and their world is a manifestation of their own guilt." },
  { modifier: "Frame the tale as an ancient prophecy that slowly reveals its terrifying accuracy." },
  { modifier: "Set the horror within a dream that feels too real - and the protagonist can’t wake up." },
  { modifier: "Introduce a character who is haunted by their own future self, trying to warn them of a terrible fate." },
  { modifier: "Have the protagonist discover a series of paintings - each one depicting their future demise." },
  { modifier: "Tell it from the perspective of a ghost who doesn’t know they’re dead yet, searching for their killer." },
  { modifier: "Make the antagonist a version of the protagonist, twisted by their own darkest desires and guilt." },
  { modifier: "Set the story inside a library where every book is a life that could have been - and the protagonist’s book is empty." },
  { modifier: "Introduce a world where the protagonist is the villain in everyone else’s story, but they never knew." },
  { modifier: "Frame it as a slow-motion descent into madness - where the protagonist can’t tell what’s real anymore." },
  { modifier: "Have the protagonist find a message in a bottle - from someone who should be long dead." },
  { modifier: "Set it within a desolate hotel where every guest has a dark secret - and one of them is still there." },
  { modifier: "Let the horror emerge from the protagonist’s childhood, where something they forgot has now returned." },
  { modifier: "Introduce a curse where every lie the protagonist tells becomes true in terrifying ways." },
  { modifier: "Set the story within a fog-covered city where the streets keep rearranging themselves at night." },
  { modifier: "Make the horror emotional rather than physical - a grief so deep it begins to manifest physically around the protagonist." },
  { modifier: "Frame the tale around a failed attempt at immortality - where the protagonist must now deal with the consequences." },
  { modifier: "Set it in a seemingly perfect utopia where everything is provided for, but the protagonist is too curious for their own good." },
  { modifier: "Introduce a being that haunts the protagonist not with violence, but with unbearable silence and stillness." },
  { modifier: "Have the protagonist uncover a map that shows them where they will die - and it’s not far off." },
  { modifier: "Set it in a seemingly normal town where everyone is an imposter, and the protagonist is the only real person left." },
  { modifier: "Frame the story around a character who is slowly realizing that their entire life has been a scripted nightmare." },
  { modifier: "Tell it through a series of notes left behind by the protagonist, who is slowly losing their memory and their grip on reality." },
  { modifier: "Set the story inside a house that grows when you’re not looking, and shrinks when you try to escape." },
  { modifier: "Let the protagonist become obsessed with something they can't see - a presence that keeps getting closer." },
  { modifier: "Frame it as a story of two lovers whose reunion sparks an ancient curse that neither can escape." },
  { modifier: "Introduce a world where the protagonist becomes trapped in a single moment, replaying it endlessly until they find the key to escaping." },
  { modifier: "Set it within a city where the protagonist is the only one who can see the cracks in reality - and they can’t fix them." },
  { modifier: "Frame the story as a mystery within a mystery, where the protagonist is unraveling a series of interconnected lies." },
  { modifier: "Tell it as a story of lost memories, where the protagonist uncovers secrets they didn’t want to know." },
  { modifier: "Set the horror in a place that shouldn’t exist - a void between realities where the rules of time and space don’t apply." },
  { modifier: "Frame it around a painting that seems to change every time the protagonist looks at it, revealing new horrors." },
  { modifier: "Introduce a world where the protagonist’s greatest fears take on physical form and stalk them wherever they go." },
  { modifier: "Set the story in a dimension where nothing is quite what it seems - and the protagonist is left to figure it out." },
  { modifier: "Let the protagonist's body betray them, slowly decaying, aging, or transforming in impossible ways." },
  { modifier: "Set the horror in a world where the protagonist can never leave, but it keeps pretending they’re free to go." },
  { modifier: "Frame the story around a character who learns that they’ve been living in a simulation - and the world is coming apart." },
  { modifier: "Introduce a character who knows everything that will happen, but can’t stop it from unfolding." },
  { modifier: "Set the tale in a place where the rules of physics are warped - and the protagonist is trying to survive without understanding why." },
  { modifier: "Turn the protagonist’s greatest fear into reality by the end of the story." },
  { modifier: "Reveal that the protagonist is the villain all along, but they don't realize it." },
  { modifier: "End the story with the suggestion that the haunting was a product of the protagonist’s guilt." },
  { modifier: "The twist is that the ‘ghost’ is a living person, but one who has been manipulated into thinking they’re dead." },
  { modifier: "Introduce a new character late in the story who claims to know the protagonist’s secret." },
  { modifier: "The antagonist turns out to be the protagonist's future self, trapped in time." },
  { modifier: "The story ends with the protagonist realizing they’ve been living in a dream all along." },
  { modifier: "The protagonist believes they’re uncovering a great mystery, but in the end, they were being watched by a higher power." },
  { modifier: "Reveal that the house or location is not haunted by ghosts but by a deep, primal fear ingrained in the land itself." },
  { modifier: "Make it so that the horrific events are all the result of a curse or ritual gone wrong years before." },
  { modifier: "At the end of the story, the protagonist discovers they are not in the world they thought they were, but in a parallel reality." },
  { modifier: "The 'haunted house' is revealed to be a metaphor for the protagonist’s fractured mind." },
  { modifier: "Twist the ending to reveal that the protagonist is stuck in an endless loop, living the same terrifying events repeatedly." },
  { modifier: "The villain is revealed to be the protagonist’s own alter ego, a darker side they’ve suppressed." },
  { modifier: "Reveal that the protagonist was dead all along, and the entire story took place in their final moments." },
  { modifier: "Have the protagonist discover they are in a simulation, and the horror was designed to keep them trapped." },
  { modifier: "Introduce a twist where the protagonist realizes they are the one causing the supernatural events, whether intentionally or not." },
  { modifier: "Turn the story around by revealing that the protagonist is the ghost, and the living people are actually the haunting." },
  { modifier: "The protagonist’s descent into madness is revealed to be the true horror, not the supernatural events." },
  { modifier: "At the end, reveal that the protagonist has been living through the same tragic event for years, and it’s never stopped." },
  { modifier: "Make it so that the protagonist’s supernatural powers are not a gift but a curse that slowly consumes them." },
  { modifier: "The twist is that the protagonist finds out they were the cause of the death or tragedy that started the haunting." },
  { modifier: "The villain is someone the protagonist trusted implicitly, and the real threat comes from betrayal." },
  { modifier: "Reveal that the ominous figure or supernatural entity has been trying to protect the protagonist all along." },
  { modifier: "Introduce a twist where the protagonist, in trying to escape the horror, ends up bringing it back with them." },
  { modifier: "The story ends with the protagonist realizing the real horror was their inability to escape their own mind." },
  { modifier: "Reveal that the ‘haunted’ house was a psychological experiment, and the protagonist is part of a larger study." },
  { modifier: "At the end, it’s revealed that everything the protagonist experienced was actually a mental illness, not a supernatural event." },
  { modifier: "The protagonist’s worst fear materializes, but the true horror is that it’s part of who they are, not something external." },
  { modifier: "The horror isn’t a ghost but a relentless, creeping feeling of dread that takes over the protagonist's mind." },
  { modifier: "End with the revelation that the protagonist is living in someone else’s memory, and the events are all illusions." },
  { modifier: "The twist is that the protagonist’s family has been hiding a dark secret that has caused the supernatural events." },
  { modifier: "Reveal that the protagonist is not haunted by ghosts but by their own repressed memories." },
  { modifier: "The twist is that the supernatural events are a manifestation of the protagonist’s own unresolved trauma." },
  { modifier: "Introduce a twist where the house or location seems safe, but everything familiar begins to feel alien and untrustworthy." },
  { modifier: "The twist is that the protagonist is not seeing ghosts, but reliving moments from their past in a disturbing new light." },
  { modifier: "Reveal that the supernatural events are actually happening in the protagonist’s mind, and they can’t trust their own senses." },
  { modifier: "At the end of the story, reveal that the haunting is a warning about something the protagonist is doing wrong." },
  { modifier: "The protagonist discovers that the ghosts are just memories of lost loved ones, and the real horror is moving on." },
  { modifier: "The twist is that the protagonist’s obsession with solving the mystery only leads them into more danger." },
  { modifier: "Have the protagonist finally solve the mystery, only to discover that the truth is far worse than any supernatural event." },
  { modifier: "Reveal that the villain is an alien being who has been manipulating the protagonist’s reality." },
  { modifier: "Introduce a twist where the villain is actually an old friend or family member who has been hiding their true nature." },
  { modifier: "The twist is that the protagonist’s ‘haunting’ is a reflection of their own inner demons manifesting in the world around them." },
  { modifier: "End with the suggestion that the supernatural event was a test, and the protagonist passed it - or failed it." },
  { modifier: "The twist is that the protagonist is not haunted by ghosts, but is being manipulated by someone they trust." },
  { modifier: "Reveal that the protagonist was unknowingly involved in a ritual or occult practice that has unleashed the haunting." },
  { modifier: "The villain is revealed to be a figure from the protagonist’s past who has returned for vengeance." },
  { modifier: "Introduce a twist where the protagonist unknowingly performs a ritual that frees the ghosts, causing more chaos." },
  { modifier: "The twist is that the protagonist’s family has been hiding the truth about the house or location, and they knew the horror would happen." },
  { modifier: "The story ends with the protagonist finally escaping, only to find the horror has followed them to a new location." },
  { modifier: "The twist is that the supernatural events aren’t happening in the house but in the protagonist’s mind." },
  { modifier: "Introduce a twist where the protagonist’s attempts to escape the haunting only make things worse, drawing them deeper into danger." },
  { modifier: "Reveal that the protagonist was unknowingly involved in causing the haunting, and now they must atone for their actions." },
  { modifier: "End with the suggestion that the protagonist’s quest for answers was all a distraction from the real horror lurking within themselves." },
  { modifier: "Have the protagonist discover that the supernatural events are tied to an ancient prophecy they can’t escape." },
  { modifier: "The twist is that the ghost or villain is someone who was once close to the protagonist, now seeking revenge." },
  { modifier: "Reveal that the haunted house is part of an elaborate game designed to trap and manipulate the protagonist." },
  { modifier: "Introduce a twist where the protagonist becomes the villain, slowly unraveling and becoming the thing they feared." },
  { modifier: "End with the shocking revelation that the protagonist has been unknowingly complicit in the terror they’ve been facing." },
  { modifier: "Have the protagonist discover a deep, horrifying secret about themselves that explains the supernatural events." },
  { modifier: "The twist is that the protagonist’s memories are false, and everything they thought was true is a lie." },
  { modifier: "The story ends with the protagonist realizing they were part of a supernatural plot all along, from the beginning." },
  { modifier: "Introduce a twist where the protagonist becomes a pawn in a larger game, manipulated by external forces they can’t comprehend." },
  { modifier: "Reveal that the horror was caused by something the protagonist did long ago, and it’s been haunting them ever since." },
  { modifier: "Have the protagonist try to fix the problem, only to make it worse and summon more supernatural forces." },
  { modifier: "End with a twist where the protagonist’s pursuit of revenge or justice only leads them into more danger and death." },
  { modifier: "The twist is that the protagonist was unknowingly marked for death, and the horror was destined to find them." },
  { modifier: "Reveal that the supernatural events are part of an elaborate trick or illusion designed to break the protagonist’s mind." },
  { modifier: "Introduce a twist where the protagonist realizes they’re trapped in a time loop, reliving the same terrifying events repeatedly." },
  { modifier: "Reveal that the protagonist is actually the one being hunted, and the ghosts or villains are simply trying to escape them." },
  { modifier: "End with the suggestion that the protagonist is the ghost all along, and they’ve been haunting their own story." },
  { modifier: "Reveal that the protagonist’s mind is the true source of the horror, and they have been creating the haunting themselves." },
  { modifier: "End with the shocking realization that the entire haunting was just a manifestation of the protagonist’s unresolved grief." },
  { modifier: "At the end, the protagonist discovers they have been the villain all along, without realizing it." },
  { modifier: "Reveal that the ‘haunting’ was a result of the protagonist’s mind playing tricks on them." },
  { modifier: "The protagonist’s descent into madness is revealed to be the true horror, not the supernatural events." },
  { modifier: "The twist is that the ‘ghost’ is actually the protagonist’s lost loved one, trying to communicate one final time." },
  { modifier: "The protagonist learns that they’ve been reliving the same tragic event over and over, each time with no memory of the previous one." },
  { modifier: "The villain is revealed to be someone the protagonist has trusted all along, manipulating them from the shadows." },
  { modifier: "Introduce a twist where the supernatural events are a test, and the protagonist must make a choice to escape." },
  { modifier: "The antagonist turns out to be the protagonist’s future self, trapped in a different time." },
  { modifier: "The protagonist discovers they’ve been trapped in a nightmare, and the supernatural events are their subconscious’ way of trying to wake them." },
  { modifier: "Reveal that the horror is tied to the protagonist’s guilt, and they must confront their past to end the torment." },
  { modifier: "The protagonist realizes they are not in the real world, but trapped in an alternate dimension of their own creation." },
  { modifier: "The twist is that the ‘ghosts’ are actually time travelers, stuck in the same loop as the protagonist." },
  { modifier: "The protagonist discovers they have been cursed, and the supernatural events are a manifestation of the curse." },
  { modifier: "At the end, it’s revealed that the protagonist is the one who invited the horrors into their life unknowingly." },
  { modifier: "The protagonist discovers that they are trapped in a simulation, and the horrors are the result of a glitch." },
  { modifier: "The villain is someone the protagonist hasn’t seen in years, but who has been controlling their every move." },
  { modifier: "The twist is that the protagonist’s attempts to fight the supernatural only empower it further." },
  { modifier: "Reveal that the ghost is a version of the protagonist from a different timeline, trying to warn them." },
  { modifier: "The protagonist’s greatest fear comes to life, and they must face it head-on to survive." },
  { modifier: "Introduce a twist where the protagonist discovers that the supernatural events are a product of their own repressed memories." },
  { modifier: "Reveal that the horror was never real, but a figment of the protagonist’s imagination, fueled by guilt." },
  { modifier: "At the end, the protagonist learns that they have been the source of the curse all along." },
  { modifier: "The twist is that the protagonist was the one who killed their own family, but their mind has erased the memory." },
  { modifier: "Reveal that the protagonist was dead all along, and the entire story was their descent into the afterlife." },
  { modifier: "The protagonist discovers they are being haunted by their own future self, warning them about a terrible fate." },
  { modifier: "The twist is that the supernatural events were orchestrated by the protagonist’s family to teach them a lesson." },
  { modifier: "Introduce a twist where the protagonist finds out that they have been in the ‘haunted’ house before in a past life." },
  { modifier: "The protagonist learns that the ‘ghosts’ they’ve been seeing are the manifestations of their own psyche." },
  { modifier: "Reveal that the protagonist’s memories have been altered, and they’ve been living a life that isn’t their own." },
  { modifier: "The twist is that the protagonist’s fear of the supernatural is actually the reason the haunting is happening." },
  { modifier: "The villain is revealed to be a ghost from the protagonist’s past, seeking revenge for a wrong that was never righted." },
  { modifier: "At the end, the protagonist discovers that they were unknowingly part of the supernatural event from the beginning." },
  { modifier: "The twist is that the protagonist has been in the haunted location for years, but they’ve been unable to remember the past." },
  { modifier: "The protagonist learns that they’ve been cursed by a powerful entity, and they must perform a ritual to lift it." },
  { modifier: "The story ends with the protagonist realizing that the haunting was a manifestation of their own trauma." },
  { modifier: "Reveal that the antagonist is a friend or loved one who has been hiding a dark secret for years." },
  { modifier: "The twist is that the protagonist’s search for answers leads them into more danger, instead of finding the truth." },
  { modifier: "The protagonist learns that the haunting was a test - and they failed, with tragic consequences." },
  { modifier: "Introduce a twist where the protagonist discovers they’ve been part of a supernatural experiment all along." },
  { modifier: "Reveal that the supernatural events are being caused by a secret society that has been manipulating the protagonist’s life." },
  { modifier: "The twist is that the protagonist is the one who summoned the entity, unknowingly triggering the haunting." },
  { modifier: "At the end, the protagonist realizes that the true horror is the fact that they are the one who is trapped." },
  { modifier: "The protagonist learns that the haunting is tied to an ancient prophecy, and they are destined to be a part of it." },
  { modifier: "The twist is that the protagonist’s family has been hiding the truth about the house and its history for years." },
  { modifier: "Introduce a twist where the protagonist is not the main character, but an observer of someone else’s tragedy." },
  { modifier: "Reveal that the ‘haunting’ is a curse placed upon the protagonist’s family for generations." },
  { modifier: "The protagonist learns that the ghost they’ve been seeing is actually trying to protect them, not harm them." },
  { modifier: "The twist is that the protagonist’s memories are false, and they’ve been living in a fabricated reality all along." },
  { modifier: "The antagonist is revealed to be an entity that feeds off the protagonist’s fear, growing stronger with each passing moment." },
  { modifier: "At the end, the protagonist discovers that the entity they’ve been fighting is a reflection of themselves." },
  { modifier: "The twist is that the supernatural events are happening in a different time period, and the protagonist is stuck in a time loop." },
  { modifier: "The protagonist learns that the horror they’ve been experiencing is not a supernatural event, but a breakdown of their own mind." },
  { modifier: "Introduce a twist where the protagonist’s descent into madness is the real horror, not the ghosts or entities." },
  { modifier: "Reveal that the house is a living entity, and the protagonist’s presence is what keeps it alive." },
  { modifier: "The twist is that the protagonist’s actions have been slowly destroying the world around them, and the horror is a result of their choices." },
  { modifier: "At the end, the protagonist learns that they are not the hero of the story, but a part of the horror they’ve been running from." },
  { modifier: "The twist is that the protagonist was unknowingly cursed by an ancient artifact, which has been tormenting them for years." },
  { modifier: "Introduce a twist where the protagonist’s attempts to escape the horror only draw them deeper into it." },
  { modifier: "Reveal that the supernatural events are all linked to a childhood trauma that the protagonist has repressed." },
  { modifier: "The twist is that the protagonist has been haunted by a future version of themselves, who is trying to change the past." },
  { modifier: "At the end, the protagonist discovers that the true horror is their own inability to let go of the past." },
  { modifier: "The twist is that the supernatural events are a reflection of the protagonist’s unresolved guilt and regret." },
  { modifier: "Reveal that the villain is someone the protagonist trusted all along, but they were always a part of the supernatural event." },
  { modifier: "The protagonist discovers they are being controlled by an external force, and they can’t escape it." },
  { modifier: "At the end, the protagonist realizes that the horror they’ve been facing is an illusion created by their own mind." },
  { modifier: "The twist is that the haunting is a result of the protagonist’s own self-destructive behavior." },
  { modifier: "The protagonist learns that the supernatural entity they’ve been fighting is actually trying to help them, not harm them." },
  { modifier: "Reveal that the protagonist was unknowingly part of an occult ritual, and the supernatural events are a consequence of their involvement." },
  { modifier: "The twist is that the protagonist has been living in a false reality created by a malevolent force." },
  { modifier: "Introduce a twist where the protagonist’s memories are false, and they’ve been living a life designed to keep them trapped." },
  { modifier: "At the end, the protagonist discovers that they are part of the supernatural event, not an innocent bystander." },
  { modifier: "The protagonist is revealed to be the monster they’ve been searching for all along." },
  { modifier: "At the end, the protagonist realizes they’ve been trapped in the same terrifying scenario for years." },
  { modifier: "The ghost is actually a projection of the protagonist’s inner guilt, but they don’t know it." },
  { modifier: "The supernatural events are caused by a family curse that the protagonist must unravel." },
  { modifier: "The twist is that the protagonist is living in someone else’s memory, and their reality is a false construct." },
  { modifier: "The horror is revealed to be a manifestation of the protagonist’s deepest fears about their own identity." },
  { modifier: "At the end, the protagonist learns that they have been dead all along, and everything is a vision of their last moments." },
  { modifier: "The villain is someone who has been manipulating the protagonist’s reality to drive them mad." },
  { modifier: "The protagonist discovers that they are trapped in a cyclical time loop and everything they’ve experienced repeats endlessly." },
  { modifier: "Reveal that the protagonist has been unknowingly participating in a dark ritual to summon the supernatural forces." },
  { modifier: "The house itself is revealed to be alive, feeding off the fear of its occupants." },
  { modifier: "The twist is that the protagonist is haunted by memories of their own past actions, which they’ve repressed." },
  { modifier: "At the end, the protagonist discovers that the ghosts are actually echoes of their own future self." },
  { modifier: "The supernatural occurrences are a result of an old curse placed on the protagonist’s family, and it’s finally coming to fruition." },
  { modifier: "The protagonist learns that they have been unknowingly living in someone else’s nightmare, and now it’s their turn to face the horror." },
  { modifier: "Reveal that the antagonist is a version of the protagonist from an alternate reality who is seeking to replace them." },
  { modifier: "The protagonist’s efforts to escape the horror only lead them deeper into the nightmare they’ve been trying to avoid." },
  { modifier: "At the end, the protagonist uncovers the true horror: they’ve been controlling everything from the start, unknowingly." },
  { modifier: "The twist is that the villain is a former version of the protagonist, trying to prevent the horrors from unfolding." },
  { modifier: "The protagonist discovers that the supernatural events are tied to their own mind’s unraveling, not an external force." },
  { modifier: "The protagonist’s entire life has been a simulation, and the supernatural events are glitches in the system." },
  { modifier: "Reveal that the protagonist’s reality has been altered, and they’ve been living in a dream created by an unseen force." },
  { modifier: "The protagonist learns that the haunting is connected to a family secret that has been buried for generations." },
  { modifier: "The twist is that the antagonist has been manipulating the protagonist’s memories, erasing and replacing them with lies." },
  { modifier: "At the end, the protagonist learns that the supernatural forces they’ve been fighting are part of their own subconscious mind." },
  { modifier: "The twist is that the protagonist is being watched by an alien race, and the supernatural events are a result of their experimentation." },
  { modifier: "The horror is revealed to be a psychological condition that the protagonist has been suffering from, not supernatural at all." },
  { modifier: "Introduce a twist where the protagonist discovers that the ghost they’ve been seeing is actually a reflection of their own psyche." },
  { modifier: "Reveal that the protagonist has been the ghost haunting the house, and they’ve been living in their own afterlife." },
  { modifier: "The twist is that the protagonist’s actions are unknowingly triggering the supernatural events." },
  { modifier: "At the end, the protagonist discovers that they’ve been living in a different timeline all along, and the horror is an inevitable consequence." },
  { modifier: "The protagonist’s obsession with the supernatural events leads them to discover that they are the true villain." },
  { modifier: "Reveal that the protagonist’s family is cursed, and they’ve been unknowingly carrying on the curse for generations." },
  { modifier: "The protagonist learns that the supernatural events are actually a result of their own hidden desires and suppressed emotions." },
  { modifier: "At the end, the protagonist is forced to confront the fact that the horror is an extension of their own inner darkness." },
  { modifier: "The twist is that the protagonist’s quest to solve the mystery only brings them closer to the source of the horror." },
  { modifier: "The protagonist discovers that the ghost they’ve been seeing is a future version of themselves, trapped in time." },
  { modifier: "Reveal that the protagonist’s obsession with solving the mystery is actually what caused the haunting in the first place." },
  { modifier: "At the end, the protagonist learns that they’ve been unknowingly part of a ritual to summon the very forces they’ve been fighting." },
  { modifier: "The protagonist’s search for answers leads them to uncover their own dark secret, which has caused the supernatural events." },
  { modifier: "Reveal that the protagonist’s family has been hiding a dark past, and the supernatural events are connected to it." },
  { modifier: "The twist is that the protagonist is unknowingly following in the footsteps of their ancestors, doomed to repeat their mistakes." },
  { modifier: "At the end, the protagonist learns that the supernatural events are actually a manifestation of their own repressed trauma." },
  { modifier: "Reveal that the antagonist is a version of the protagonist from a parallel universe who has been trying to warn them." },
  { modifier: "Introduce a twist where the protagonist is revealed to be the one who summoned the supernatural entity by accident." },
  { modifier: "The twist is that the protagonist has been haunted by a past life, and the events they’ve been experiencing are echoes from it." },
  { modifier: "At the end, the protagonist learns that they are the one who is cursed, and they must break the curse to end the terror." },
  { modifier: "The villain is revealed to be a powerful being who has been manipulating the protagonist’s fate for years." },
  { modifier: "The protagonist discovers that they’ve been living in a dream constructed by a malevolent force, and it’s beginning to break down." },
  { modifier: "Reveal that the protagonist’s quest for answers is actually leading them straight into the heart of the horror they’ve been trying to escape." },
  { modifier: "The twist is that the supernatural events are a result of the protagonist’s own wishes coming true, but at a terrible cost." },
  { modifier: "At the end, the protagonist realizes that the horror they’ve been facing was always a part of them." },
  { modifier: "Introduce a twist where the protagonist is unknowingly the reincarnation of a tragic figure from history, and they must fulfill their destiny." },
  { modifier: "The protagonist uncovers a hidden history of the house they’ve been living in, and it’s tied to a horrific event from the past." },
  { modifier: "Reveal that the supernatural forces are a result of the protagonist’s deep-seated fears and anxieties manifesting in the physical world." },
  { modifier: "At the end, the protagonist learns that the horror was a test all along, and they failed." },
  { modifier: "The twist is that the villain is a version of the protagonist from the future, sent to prevent them from making the same mistakes." },
  { modifier: "The protagonist’s search for answers leads them to uncover a disturbing truth about their own identity." },
  { modifier: "Reveal that the protagonist’s memories have been altered, and they are not who they think they are." },
  { modifier: "At the end, the protagonist learns that the ghost or entity they’ve been fighting is actually trying to protect them from something worse." },
  { modifier: "Introduce a twist where the protagonist learns that they are not the hero, but the unwitting villain of the story." },
  { modifier: "The twist is that the supernatural forces are a reflection of the protagonist’s guilt over an unspeakable crime." },
  { modifier: "At the end, the protagonist learns that the horror was never real, but a figment of their own fractured mind." },
  { modifier: "The protagonist is forced to confront the terrifying truth: the horror they’ve been experiencing is a result of their own choices." },
  { modifier: "Reveal that the antagonist is an ancient entity who has been manipulating the protagonist’s reality for centuries." },
  { modifier: "The protagonist learns that the supernatural events are tied to a curse placed on their family generations ago." },
  { modifier: "At the end, the protagonist discovers that the supernatural events are a manifestation of their own repressed memories." },
  { modifier: "Introduce a twist where the protagonist realizes they are not living in the world they thought they were, but in a different reality." },
  { modifier: "The twist is that the protagonist’s obsession with the supernatural forces only serves to empower them further." },
  { modifier: "At the end, the protagonist discovers that they’ve been the source of the supernatural events all along, without knowing it." },
  { modifier: "At the end, the protagonist realizes they were the antagonist all along, manipulating events from the shadows." },
  { modifier: "The supernatural force is revealed to be a reflection of the protagonist's darkest desires." },
  { modifier: "The horror is not supernatural, but the result of the protagonist’s unresolved trauma." },
  { modifier: "Reveal that the haunting is a manifestation of the protagonist’s guilt for something they did years ago." },
  { modifier: "The protagonist learns that they have been dead all along, and the whole story was their afterlife." },
  { modifier: "The villain is revealed to be someone the protagonist trusted implicitly, controlling their every move." },
  { modifier: "The protagonist discovers they’ve been living in a loop, experiencing the same nightmare over and over." },
  { modifier: "The twist is that the ghost is a future version of the protagonist, warning them of their fate." },
  { modifier: "At the end, the protagonist learns that they were always part of the haunting, a puzzle piece in the curse." },
  { modifier: "Reveal that the protagonist's memories have been manipulated, and they have been living in a constructed reality." },
  { modifier: "The story ends with the protagonist finding out that they’ve been the cause of the supernatural events all along." },
  { modifier: "The protagonist realizes that the ‘haunting’ was never real; it was the result of their own psychological unraveling." },
  { modifier: "The twist is that the protagonist's obsession with the supernatural is actually driving the horrors they face." },
  { modifier: "At the end, it’s revealed that the protagonist was the one who summoned the haunting by unknowingly performing a ritual." },
  { modifier: "The protagonist learns that the villain is an ancient force manipulating their reality for its own gain." },
  { modifier: "The twist is that the supernatural entity is trying to protect the protagonist from something even worse." },
  { modifier: "The protagonist is forced to confront the fact that they are the one who doomed themselves from the beginning." },
  { modifier: "Reveal that the ghosts are actually the echoes of people the protagonist has wronged, seeking revenge." },
  { modifier: "At the end, the protagonist realizes that they’ve been living in someone else’s nightmare all along." },
  { modifier: "The twist is that the house itself is a sentient being, and it has been manipulating the protagonist’s actions." },
  { modifier: "The protagonist’s family has been hiding a dark secret, and the house is a reflection of that secret." },
  { modifier: "The protagonist learns that the supernatural forces are tied to an ancient prophecy, and they are the key to its fulfillment." },
  { modifier: "At the end, the protagonist realizes that the horror they’ve been facing was created by their own mind." },
  { modifier: "The twist is that the protagonist is being watched by an unseen force, manipulating their every move." },
  { modifier: "Reveal that the villain is not a person, but a manifestation of the protagonist’s subconscious mind." },
  { modifier: "The protagonist’s search for answers leads them into more danger, revealing their own complicity in the supernatural events." },
  { modifier: "The twist is that the protagonist is unknowingly causing the supernatural events to unfold with every choice they make." },
  { modifier: "At the end, the protagonist learns that the haunting is a result of their own repressed memories coming to light." },
  { modifier: "The protagonist is revealed to have been part of the villain’s plan all along, unknowingly working toward the supernatural goal." },
  { modifier: "Reveal that the villain is a version of the protagonist from the future, trying to prevent the horrors they’re destined to cause." },
  { modifier: "The twist is that the supernatural events are actually a psychological experiment being conducted on the protagonist." },
  { modifier: "At the end, the protagonist discovers that they have been living in a simulation, and everything they’ve experienced was controlled." },
  { modifier: "The protagonist learns that the supernatural force is a reflection of their own guilt, which has manifested physically." },
  { modifier: "Reveal that the protagonist has been living in a false reality for years, and everything they thought was real is an illusion." },
  { modifier: "The twist is that the protagonist’s attempts to escape the horror only make it stronger, drawing them deeper into the supernatural world." },
  { modifier: "At the end, the protagonist discovers that the supernatural force is trying to help them escape a terrible fate." },
  { modifier: "The protagonist’s obsession with the supernatural forces only leads them to uncover a terrible truth about their own past." },
  { modifier: "The twist is that the protagonist’s own actions have been triggering the supernatural events without them realizing it." },
  { modifier: "At the end, the protagonist learns that the haunting is tied to an old family secret, one that they must confront to end it." },
  { modifier: "The twist is that the supernatural entity is a manifestation of the protagonist’s deepest fear, and only by facing it can they escape." },
  { modifier: "Reveal that the villain is a ghost who is trying to warn the protagonist about something terrible in the future." },
  { modifier: "At the end, the protagonist realizes they are not in the real world, but trapped in a dream created by an outside force." },
  { modifier: "The twist is that the protagonist’s memories are false, and they have been living in a life they didn’t create." },
  { modifier: "Reveal that the supernatural force has been manipulating the protagonist for years, and they are its puppet." },
  { modifier: "The protagonist learns that they are the source of the supernatural events, and they have been unknowingly summoning the horrors." },
  { modifier: "At the end, the protagonist discovers that the haunting is a consequence of a choice they made long ago, and now they must live with it." },
  { modifier: "The twist is that the protagonist is actually the one who invited the supernatural entity into their life without knowing it." },
  { modifier: "The villain is revealed to be the protagonist’s own reflection, trying to destroy them." },
  { modifier: "Reveal that the protagonist’s attempts to escape the horror are futile, and they are trapped in an endless loop of terror." },
  { modifier: "At the end, the protagonist learns that they are the one who has been haunting the house, and they’ve been dead all along." },
  { modifier: "The twist is that the supernatural entity is not trying to hurt the protagonist, but to guide them to a terrible truth." },
  { modifier: "Reveal that the protagonist is living in a different timeline, and the supernatural events are a consequence of their actions in the past." },
  { modifier: "The twist is that the protagonist’s greatest fear is not a ghost or entity, but the realization that they are the cause of the terror." },
  { modifier: "At the end, the protagonist learns that the supernatural forces are part of a larger cosmic plan that they have no control over." },
  { modifier: "The protagonist realizes they’ve been part of a grand experiment, and the supernatural events were designed to test them." },
  { modifier: "Reveal that the antagonist is an ancient force that has been manipulating the protagonist for centuries." },
  { modifier: "The twist is that the supernatural events are a result of the protagonist’s own desire for power, which has corrupted them." },
  { modifier: "At the end, the protagonist discovers that they’ve been living in a false reality, and the horror was a side effect of their broken mind." },
  { modifier: "The twist is that the protagonist is unknowingly the villain, and the horror has been a consequence of their own actions." },
  { modifier: "Reveal that the protagonist is trapped in a different dimension, and the supernatural events are a reflection of their fears." },
  { modifier: "At the end, the protagonist learns that the horror they’ve been facing was never real, but a result of their own self-doubt." },
  { modifier: "The twist is that the protagonist has been the ghost haunting the house, but they’ve been unaware of it." },
  { modifier: "Reveal that the villain is an ancient entity that has been manipulating the protagonist’s actions for centuries." },
  { modifier: "The twist is that the supernatural events are a product of the protagonist’s own fractured mind, breaking down reality." },
  { modifier: "At the end, the protagonist discovers that the haunting is tied to an old family secret they must uncover to end the terror." },
  { modifier: "Introduce a twist where the protagonist is unknowingly part of the haunting, and they must confront their own role in it." },
  { modifier: "Reveal that the supernatural events are a manifestation of the protagonist’s own unresolved grief and trauma." },
  { modifier: "At the end, the protagonist learns that the true horror is not the ghost, but the lies they’ve been living." },
  { modifier: "Reveal that the protagonist’s attempts to escape the horror only lead them deeper into the nightmare." },
  { modifier: "Introduce a twist where the protagonist’s greatest fear is themselves, and they must confront their own inner darkness." },
  { modifier: "At the end, the protagonist learns that they have been a part of a grand illusion created to break their mind." },
  { modifier: "Reveal that the protagonist’s family has been hiding the truth about their past, and the supernatural events are tied to that." },
  { modifier: "The twist is that the protagonist’s memories are false, and the events they’ve been experiencing were altered to hide the truth." },
];
